export const TEAM_NAMES = ['Fisher', 'Neyman', 'Rubin', 'Pearl', 'Robins', 'Imbens', 'Rosenbaum']
export const ROLES = [
  { code: 'business', label: 'Líder de Decisión y Política', question: '¿Qué decisión necesitamos tomar, bajo qué restricción y con qué política?', core:true },
  { code: 'data', label: 'Líder de Modelos', question: '¿Qué dice el modelo y qué NO dice?', core:true },
  { code: 'context', label: 'Analista Causal', question: '¿Qué estructura causal hace válida o inválida la comparación?', core:true },
  { code: 'integrator', label: 'Líder de Experimentos', question: '¿Qué diseño permite estimar un efecto defendible?', core:true }
]
export const CORE_ROLES=ROLES.filter(r=>r.core)
export const MICROCHECKS = {
  1:{prompt:'ORÁCULO tiene AUC alta. En el sandbox, A tendría 90% con llamada y 89% sin llamada; B, 65% con llamada y 35% sin llamada. Si sólo puedes intervenir a uno, ¿a quién priorizas por impacto incremental?',options:['A','B','A, porque 90% es la mayor probabilidad observada','No se puede priorizar: una AUC alta reemplaza el efecto causal'],concept:'Predicción vs impacto causal'},
  2:{prompt:'La comparación cruda da −12 pp; regresión ajustada +3.9 pp e IPW +4.2 pp. Además, los llamados tenían mayor mora desde antes y la mora reduce el pago. ¿Qué problema sigue siendo central aunque dos métodos ajustados coincidan?',options:['Los grupos no son comparables desde antes','La coincidencia entre métodos demuestra identificación causal','El tamaño de muestra invalida automáticamente el análisis','IPW elimina cualquier confusión, incluso la no medida'],concept:'Confusión e identificación'},
  3:{prompt:'En un experimento aleatorio, tratamiento convierte 31% y control 25%. El IC95% de la diferencia no incluye 0. ¿Cuál es la lectura correcta del efecto promedio en la escala mostrada?',options:['6 puntos porcentuales','6% relativo','Cada persona mejora exactamente 6 puntos porcentuales','El resultado demuestra que todos los segmentos tienen efecto positivo'],concept:'ATE e incertidumbre'},
  4:{prompt:'El ATE es positivo, pero mora alta tiene efecto negativo y otro segmento tiene un IC que cruza 0. Bajo capacidad limitada, ¿qué política es más defendible?',options:['Tratar a todos porque el promedio es positivo','Priorizar segmentos con efecto positivo y evitar el segmento negativo','Elegir sólo por score predictivo','Ignorar los intervalos si CausalForestDML y DR-Learner coinciden'],concept:'Heterogeneidad, incertidumbre y política'}
}
export const ROUND_COPY = {
  1:{kicker:'RONDA 1 · ORÁCULO',title:'El modelo sabe quién convertirá',mission:'Tienen presupuesto para intervenir sólo 10 de 24 clientes. Usen las cuatro especialidades del equipo y elijan a quiénes.',teaching:{title:'Cierre: predecir no es causar',body:'Un puntaje alto responde “¿quién probablemente convertirá?”. La pregunta causal es “¿quién cambiará precisamente porque intervengo?”. El futuro que no observamos se llama contrafactual.'}},
  2:{kicker:'RONDA 2 · LA COMPARACIÓN ENGAÑOSA',title:'Las llamadas parecen empeorar el pago',mission:'Llamados pagan menos que no llamados. Integren las cuatro especialidades para decidir si cancelar, mantener o rediseñar.',teaching:{title:'Cierre: una comparación puede ser injusta',body:'Si una característica previa influye tanto en quién recibe la llamada como en la probabilidad de pago, los grupos parten de lugares distintos. A esto lo llamamos confusión. Además, debe existir solapamiento suficiente: necesitamos comparaciones plausibles para la población donde queremos aprender el efecto.'}},
  3:{kicker:'RONDA 3 · UNA PRUEBA MEJOR',title:'Necesitamos saber si realmente funciona',mission:'Hay 20.000 clientes elegibles. Diseñen cómo comparar intervención y no intervención, resultado, horizonte y precisión útil para la decisión.',teaching:{title:'Cierre: el azar construye una comparación más creíble',body:'La asignación aleatoria evita que el criterio de selección concentre sistemáticamente un tipo de cliente en un grupo. La diferencia de resultados puede interpretarse como un efecto promedio bajo el diseño del experimento; más N reduce incertidumbre, pero no corrige una asignación sesgada.'}},
  4:{kicker:'RONDA 4 · EL PROMEDIO NO CUENTA TODA LA HISTORIA',title:'Funciona… pero no para todos',mission:'El efecto promedio es positivo. Combinen identificación, efecto por segmento, incertidumbre, valor y riesgo para construir una política bajo la restricción acordada. Decisión y Política integra el cierre.',teaching:{title:'Cierre: estimar no basta; hay que desafiar la conclusión',body:'Un promedio positivo no significa que todos se beneficien. CATE ayuda a explorar heterogeneidad, pero la política sigue dependiendo de identificación defendible, incertidumbre, restricciones y pruebas de robustez.'}}
}
