import React from'react'
import{createRoot}from'react-dom/client'
import'./styles.css'
import'./quest.css'
import'./quest-v4.css'
import'./quest-v41.css'
import'./quest-v5.css'
import'./quest-v5-extra.css'
import'./quest-v5-visuals.css'
import'./role-visual.css'
import'./quest-v6.css'
import{Layout}from'./components/Layout'
import{RoleInspector}from'./components/RoleInspector'

createRoot(document.getElementById('root')).render(<Layout subtitle="Inspector docente · cinco especialistas"><RoleInspector/></Layout>)
