import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{CheckCircle2,AlertTriangle,XCircle,Laptop,Wifi,Monitor,Database,Send}from'lucide-react';import'./styles.css';import'./quest-v5.css';import{Layout}from'./components/Layout';import{health,invoke,runtimeMode}from'./lib/api';

function detect(){const ua=navigator.userAgent||'';const os=/Windows/i.test(ua)?'Windows':/Macintosh|Mac OS X/i.test(ua)?'macOS':/Linux/i.test(ua)?'Linux':/Android/i.test(ua)?'Android':/iPhone|iPad/i.test(ua)?'iOS':'Otro';const browser=/Edg\//.test(ua)?'Edge':/Chrome\//.test(ua)?'Chrome':/Safari\//.test(ua)&&!/Chrome\//.test(ua)?'Safari':/Firefox\//.test(ua)?'Firefox':'Otro';const mobile=/Android|iPhone|iPad|Mobile/i.test(ua);return{os,browser,mobile,viewport:`${window.innerWidth}×${window.innerHeight}`}}
function icon(ok){return ok===true?<CheckCircle2 className="ok"/>:ok===false?<XCircle className="bad"/>:<AlertTriangle className="warn"/>}

function App(){const meta=useMemo(detect,[]);const[name,setName]=useState('');const[code,setCode]=useState('FUTUROS26');const[backend,setBackend]=useState({ok:null,latency_ms:null});const[storage,setStorage]=useState(false);const[sent,setSent]=useState(false);const[error,setError]=useState('');const[busy,setBusy]=useState(false);
useEffect(()=>{let ok=false;try{localStorage.setItem('__cq','1');sessionStorage.setItem('__cq','1');localStorage.removeItem('__cq');sessionStorage.removeItem('__cq');ok=true}catch{}setStorage(ok);health().then(setBackend)},[])
const modern=typeof crypto?.randomUUID==='function'&&typeof fetch==='function'&&CSS?.supports?.('display','grid');const desktop=!meta.mobile;const screenOK=window.innerWidth>=900;const browserOK=['Chrome','Edge','Safari','Firefox'].includes(meta.browser);const backendOK=backend.ok===true;const latency=Number(backend.latency_ms||0);const fail=!storage||!modern||!backendOK||!desktop||!browserOK;const warn=!fail&&(!screenOK||latency>1500);const overall=fail?'fail':warn?'warn':'pass';const rows=[{name:'Equipo de escritorio',ok:desktop,detail:`${meta.os} · ${meta.device||'computador'}`,Icon:Laptop},{name:'Navegador compatible',ok:browserOK,detail:meta.browser,Icon:Monitor},{name:'Almacenamiento local',ok:storage,detail:'Necesario para recuperar la sesión al recargar.',Icon:Database},{name:'Funciones modernas',ok:modern,detail:'JavaScript, fetch, CSS Grid y UUID.',Icon:CheckCircle2},{name:'Pantalla',ok:screenOK?true:null,detail:meta.viewport,Icon:Monitor},{name:'Servidor',ok:backend.ok===null?null:backendOK,detail:backend.ok===null?'Midiendo…':backendOK?`${latency} ms`:(backend.error||'Sin conexión'),Icon:Wifi}];
async function submit(){setBusy(true);setError('');try{await invoke('readiness-check',{game_code:code,display_name:name,payload:{os:meta.os,browser:meta.browser,device:meta.mobile?'móvil':'computador',viewport:meta.viewport,backend_ms:latency,overall,checks:{storage,modern,desktop,screen:screenOK,browser:browserOK,backend:backendOK}}},'player');setSent(true)}catch(e){setError(e.message)}finally{setBusy(false)}}
return <Layout subtitle="Prueba previa"><div className="hero readiness-hero"><div className="eyebrow">CAUSAL QUEST · PRUEBA 24 HORAS ANTES</div><h2>¿Tu computador está listo para la sesión?</h2><p>Esta prueba tarda menos de 3 minutos y funciona en Windows y macOS. Para jugar recomendamos portátil o computador; no celular.</p></div><div className={`readiness-status ${overall}`}><div>{overall==='pass'?<CheckCircle2/>:overall==='warn'?<AlertTriangle/>:<XCircle/>}</div><section><div className="eyebrow">RESULTADO</div><h2>{overall==='pass'?'APTO':overall==='warn'?'APTO CON OBSERVACIONES':'NO APTO'}</h2><p>{overall==='pass'?'Tu equipo cumple las condiciones principales.':overall==='warn'?'Puedes jugar, pero revisa las observaciones antes de la sesión.':'Corrige los puntos en rojo antes de la sesión.'}</p></section></div><div className="check-grid readiness-grid">{rows.map(x=><div className="check-item" key={x.name}>{icon(x.ok)}<div><b>{x.name}</b><div style={{color:'var(--muted)',fontSize:12}}>{x.detail}</div></div></div>)}</div>{overall==='warn'&&<div className="notice notice-gold" style={{marginTop:16}}>{!screenOK?'Maximiza la ventana o usa una pantalla de al menos 900 px de ancho. ':''}{latency>1500?'La conexión está lenta; cierra descargas, VPN innecesaria o pestañas pesadas.':''}</div>}{overall==='fail'&&<div className="notice notice-red" style={{marginTop:16}}>Usa Chrome, Edge, Safari o Firefox actualizado desde un computador. Si el servidor aparece en rojo, prueba otra red o consulta con el equipo del chapter.</div>}<div className="card readiness-register"><div><div className="eyebrow">REGISTRAR TU PRUEBA</div><h3>Así sabremos si los 20 participantes están listos</h3></div><div className="grid grid-2"><label className="form-row"><span>Nombre</span><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Tu nombre"/></label><label className="form-row"><span>Código del juego</span><input className="input" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></label></div>{sent?<div className="notice notice-green"><CheckCircle2 size={18}/> Resultado registrado. Puedes cerrar esta página.</div>:<button className="btn btn-primary" disabled={busy||name.trim().length<2||backend.ok===null} onClick={submit}><Send size={16}/>{busy?'Registrando…':'Registrar resultado'}</button>}{error&&<div className="notice notice-red">{error}</div>}</div><div className="notice" style={{marginTop:18}}>Recomendado para la sesión: Chrome o Edge actualizado en Windows; Chrome, Edge o Safari actualizado en macOS. No se instala ningún programa.</div></Layout>}
createRoot(document.getElementById('root')).render(<App/>);
