import React,{useEffect,useMemo,useState}from'react'
import{createRoot}from'react-dom/client'
import{CheckCircle2,Copy,Laptop,MousePointerClick,RefreshCw,TriangleAlert,XCircle}from'lucide-react'
import'./styles.css'
import'./quest-v5.css'
import{Layout}from'./components/Layout'
import{health,runtimeMode}from'./lib/api'

function deviceInfo(){const ua=navigator.userAgent;let os=/Windows NT/i.test(ua)?'Windows':/Macintosh|Mac OS X/i.test(ua)?'macOS':/Android/i.test(ua)?'Android':/iPhone|iPad/i.test(ua)?'iOS':'Otro';let browser='Otro',version='';let m;if((m=ua.match(/Edg\/([\d.]+)/))){browser='Edge';version=m[1]}else if((m=ua.match(/Chrome\/([\d.]+)/))){browser='Chrome';version=m[1]}else if((m=ua.match(/Firefox\/([\d.]+)/))){browser='Firefox';version=m[1]}else if(/Safari\//.test(ua)&&(m=ua.match(/Version\/([\d.]+)/))){browser='Safari';version=m[1]}return{os,browser,version}}
function statusIcon(status){return status==='ok'?<CheckCircle2 className="ok"/>:status==='warn'?<TriangleAlert className="warn"/>:status==='bad'?<XCircle className="bad"/>:<RefreshCw/>}
function App(){
 const info=useMemo(deviceInfo,[]);const[checks,setChecks]=useState([]);const[interaction,setInteraction]=useState(false);const[running,setRunning]=useState(true)
 async function run(){setRunning(true);const next=[];const desktop=['Windows','macOS'].includes(info.os);next.push({name:'Equipo',status:desktop?'ok':'bad',detail:`${info.os} · esta actividad está diseñada para computador Windows o Mac.`});const supported=['Chrome','Edge','Safari','Firefox'].includes(info.browser);next.push({name:'Navegador',status:supported?'ok':'warn',detail:`${info.browser} ${info.version||''}. Recomendado: Chrome o Edge actualizado; en Mac también Safari actualizado.`});let local=false,session=false;try{localStorage.setItem('__cq','1');localStorage.removeItem('__cq');local=true}catch{}try{sessionStorage.setItem('__cq','1');sessionStorage.removeItem('__cq');session=true}catch{}next.push({name:'Guardar sesión',status:local&&session?'ok':'bad',detail:local&&session?'El navegador puede conservar tu equipo y rol al recargar.':'El almacenamiento del navegador está bloqueado.'});const grid=CSS?.supports?.('display','grid');const cryptoOk=Boolean(globalThis.crypto?.randomUUID);next.push({name:'Funciones del navegador',status:grid&&cryptoOk?'ok':'bad',detail:grid&&cryptoOk?'Gráficas, tarjetas y recuperación de sesión disponibles.':'Faltan capacidades modernas del navegador.'});const width=Math.max(screen.width,innerWidth);next.push({name:'Pantalla',status:width>=1100?'ok':width>=900?'warn':'bad',detail:`${width}px de ancho detectado. Recomendado ≥ 1100px y ventana maximizada.`});const imageOk=await new Promise(resolve=>{const im=new Image();const timer=setTimeout(()=>resolve(false),5000);im.onload=()=>{clearTimeout(timer);resolve(true)};im.onerror=()=>{clearTimeout(timer);resolve(false)};im.src=`./roles/decision-lead.webp?check=${Date.now()}`});next.push({name:'Recursos visuales',status:imageOk?'ok':'bad',detail:imageOk?'Las cartas de rol cargan correctamente.':'No cargó la imagen de prueba; revisa red, proxy o bloqueo corporativo.'});let latencies=[];let backendOk=true;let backendError='';for(let i=0;i<3;i++){try{const r=await health();if(!r.ok)backendOk=false;latencies.push(Number(r.latency_ms||0))}catch(e){backendOk=false;backendError=e.message;break}}const avg=latencies.length?Math.round(latencies.reduce((a,b)=>a+b,0)/latencies.length):null;const backendStatus=!backendOk?'bad':avg<=1500?'ok':avg<=3000?'warn':'bad';next.push({name:'Conexión al juego',status:backendStatus,detail:backendError||`${avg} ms promedio en 3 pruebas. ${avg>1500?'Puede sentirse lenta durante la partida.':'Conexión adecuada.'}`});next.push({name:'Modo de sesión',status:runtimeMode==='secure'?'ok':'warn',detail:runtimeMode==='secure'?'Conectado al entorno multiusuario real.':'Estás viendo un modo de ensayo, no el entorno real.'});setChecks(next);setRunning(false)}
 useEffect(()=>{run()},[])
 const withInteraction=[...checks,{name:'Interacción',status:interaction?'ok':'warn',detail:interaction?'Botones y animación respondieron correctamente.':'Pulsa el botón de prueba para completar el chequeo.'}];const bad=withInteraction.filter(x=>x.status==='bad').length,warn=withInteraction.filter(x=>x.status==='warn').length;const overall=running?'running':bad?'bad':warn?'warn':'ok';const label=overall==='ok'?'APTO':overall==='warn'?'APTO CON OBSERVACIONES':overall==='bad'?'NO APTO':'VERIFICANDO…';const diagnostic=`Causal Quest readiness | ${new Date().toLocaleString('es-CO')} | ${info.os} | ${info.browser} ${info.version} | ${label} | `+withInteraction.map(x=>`${x.name}:${x.status}`).join(', ')
 async function copy(){try{await navigator.clipboard.writeText(diagnostic);alert('Diagnóstico copiado. Puedes enviarlo al equipo del chapter.')}catch{alert(diagnostic)}}
 return <Layout subtitle="Prueba de preparación"><div className="readiness-hero"><div className="eyebrow">CAUSAL QUEST · PRUEBA PREVIA</div><h2>¿Tu computador está listo para la sesión?</h2><p>Haz esta prueba el día anterior. Toma cerca de 2 minutos y no instala nada.</p><div className={`readiness-status ${overall==='ok'?'good':overall==='warn'?'warn':overall==='bad'?'bad':''}`}>{statusIcon(overall==='running'?'pending':overall)} {label}</div></div><div className="readiness-grid">{withInteraction.map(x=><div className="readiness-item" key={x.name}>{statusIcon(x.status)}<div><b>{x.name}</b><small>{x.detail}</small></div></div>)}</div><div className="card" style={{marginTop:16}}><h3>Prueba de interacción</h3><p>Pulsa el botón. El círculo debe encenderse y crecer. Esto valida clic, estilos y animación básica.</p><div className="interaction-test"><button className="btn btn-primary" onClick={()=>setInteraction(true)}><MousePointerClick size={16}/> Probar interacción</button><div className={`interaction-dot ${interaction?'on':''}`}/></div></div><div className="grid grid-2" style={{marginTop:16}}><div className="card"><Laptop/><h3>Para mañana</h3><p>Usa computador, maximiza la ventana y preferiblemente Chrome o Edge actualizado. En Mac, Safari actualizado también es válido. Evita celular o tableta para jugar.</p></div><div className="card"><h3>Si sale “No apto”</h3><p>No esperes al inicio del chapter. Copia el diagnóstico y envíalo al equipo con una captura. Si sólo aparece “Apto con observaciones”, revisa el detalle antes de la sesión.</p><div className="fac-toolbar"><button className="btn" onClick={run} disabled={running}><RefreshCw size={15}/> Repetir prueba</button><button className="btn" onClick={copy}><Copy size={15}/> Copiar diagnóstico</button></div></div></div><div className="notice" style={{marginTop:16}}>Esta prueba valida tu dispositivo individual. La plataforma además se somete a pruebas automáticas de concurrencia para los 20 participantes.</div></Layout>
}
createRoot(document.getElementById('root')).render(<App/>)
