import React,{useEffect,useMemo,useState}from'react'
import{Check,ChevronRight,Lightbulb,LogOut,Users}from'lucide-react'
import{invoke,savePlayerToken,savePlayerGameCode,getPlayerToken,clearPlayerSession}from'../lib/api'
import{V2_MISSION,V2_ROUNDS,RECOMMENDATIONS,ASSIGNMENTS,OUTCOMES,HORIZONS,POLICY_ACTIONS,statusCopy}from'./content'

const jitter=n=>Math.round(n*(.85+Math.random()*.3))
const pct=n=>`${Math.round(Number(n||0)*100)}%`

function Join({onJoined}){
  const params=new URLSearchParams(location.search)
  const[code,setCode]=useState((params.get('game')||'').toUpperCase())
  const[name,setName]=useState('')
  const[busy,setBusy]=useState(false),[err,setErr]=useState('')
  async function go(){setBusy(true);setErr('');try{const r=await invoke('join-game',{game_code:code.trim().toUpperCase(),display_name:name.trim()});savePlayerToken(r.token);savePlayerGameCode(code);onJoined()}catch(e){setErr(e.message)}finally{setBusy(false)}}
  return <main className="v2-shell v2-center"><section className="v2-join-card"><div className="v2-brand">DOS FUTUROS <span>V2</span></div><div className="v2-kicker">SIMULACIÓN CAUSAL</div><h1>No necesitas aprender reglas. Sólo toma decisiones.</h1><p className="v2-lead">Todos son analistas. Cada persona verá una parte distinta del mismo problema. Primero decides tú; después hablan y deciden juntos.</p><div className="v2-rule-row">{V2_MISSION.rules.map((x,i)=><div key={x}><b>{i+1}</b><span>{x}</span></div>)}</div><label>Código de sesión<input value={code} autoCapitalize="characters" onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Ej. FUTUROS26"/></label><label>Tu nombre<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre visible"/></label>{err&&<div className="v2-alert error">{err}</div>}<button className="v2-primary" disabled={busy||code.trim().length<4||name.trim().length<2} onClick={go}>{busy?'Entrando…':'Entrar al equipo'} <ChevronRight size={18}/></button></section></main>
}

function useV2State(enabled){const[state,setState]=useState(null),[error,setError]=useState('');async function refresh(){try{const x=await invoke('v2-state');setState(x);setError('');return x}catch(e){setError(e.message);return null}}useEffect(()=>{if(!enabled)return;let stop=false,t;const loop=async()=>{await refresh();if(!stop)t=setTimeout(loop,jitter(2300))};loop();return()=>{stop=true;clearTimeout(t)}},[enabled]);return{state,error,refresh}}

function Header({state,onExit}){const r=V2_ROUNDS[state.game.round];return <header className="v2-header"><div><div className="v2-brand small">DOS FUTUROS <span>V2</span></div><strong>{state.player.team}</strong></div><div className="v2-header-center"><span>R{state.game.round}/4</span><b>{r?.title}</b></div><button className="v2-icon" onClick={onExit} title="Salir"><LogOut size={18}/></button></header>}

function MissionStrip({round}){const r=V2_ROUNDS[round];return <section className="v2-mission"><div className="v2-kicker">{r.kicker}</div><h1>{r.title}</h1><p>{r.case}</p></section>}

function Lobby({state}){return <div className="v2-main"><section className="v2-big-wait"><div className="v2-pulse"/><div className="v2-kicker">YA ESTÁS DENTRO</div><h1>{state.player.name}</h1><p>Equipo <b>{state.player.team}</b> · asiento {state.player.seat}</p><h2>Espera a que el facilitador inicie.</h2><div className="v2-team-roster">{state.team.roster.map(p=><div key={p.id} className="ready"><span>✓</span>{p.name}</div>)}</div><div className="v2-alert">No hay roles. Todos tienen el mismo poder para proponer y decidir.</div></section></div>}

function CustomerCard({c,selected,onClick,mode='score'}){return <button type="button" className={`v2-customer ${selected?'selected':''}`} onClick={onClick}><div className="v2-card-top"><span>{c.id}</span>{selected&&<Check size={17}/>}</div><h3>{c.name}</h3><small>{c.segment}</small>{mode==='score'&&<><div className="v2-score">{pct(c.score)}</div><small>probabilidad predicha</small><div className="v2-shap">{(c.shap||[]).slice(0,3).map(x=><span key={x.feature}>{x.feature}: <b>{Number(x.impact)>0?'+':''}{x.impact}</b></span>)}</div></>}{mode==='history'&&<div className="v2-history"><span>Riesgo previo <b>{c.risk}/4</b></span><span>{c.treated?'Intervenido':'No intervenido'}</span><span>Resultado <b>{c.outcome?'Sí':'No'}</b></span></div>}{mode==='sample'&&<div className="v2-history"><span>Riesgo <b>{c.risk}/4</b></span><span>Score <b>{pct(c.score)}</b></span></div>}</button>}

function Hint({text,round}){const key=`v2-hint-${round}`,initial=localStorage.getItem(key)==='1';const[open,setOpen]=useState(initial);function show(){setOpen(true);localStorage.setItem(key,'1')}return open?<div className="v2-alert hint"><Lightbulb size={18}/><span>{text}</span></div>:<button className="v2-secondary" onClick={show}><Lightbulb size={16}/> Necesito una pista</button>}

function IndividualR1({state,onSend,busy}){const[sel,setSel]=useState([]);const toggle=id=>setSel(v=>v.includes(id)?v.filter(x=>x!==id):v.length<3?[...v,id]:v);return <><div className="v2-step"><b>PASO 1 · DECIDE TÚ</b><span>{V2_ROUNDS[1].individual}</span></div><div className="v2-grid customers">{state.packet.map(c=><CustomerCard key={c.id} c={c} selected={sel.includes(c.id)} onClick={()=>toggle(c.id)}/>)}</div><div className="v2-sticky"><span>{sel.length}/3 candidatos</span><button className="v2-primary" disabled={busy||sel.length<1} onClick={()=>onSend({selected:sel})}>Enviar mi propuesta</button></div></>}

function IndividualR2({state,onSend,busy}){const[rec,setRec]=useState('');return <><div className="v2-step"><b>PASO 1 · DECIDE TÚ</b><span>{V2_ROUNDS[2].individual}</span></div><div className="v2-grid customers">{state.packet.map(c=><CustomerCard key={c.id} c={c} mode="history"/>)}</div><div className="v2-choice-row">{RECOMMENDATIONS.map(([v,l])=><button className={rec===v?'selected':''} key={v} onClick={()=>setRec(v)}>{l}</button>)}</div><button className="v2-primary wide" disabled={busy||!rec} onClick={()=>onSend({recommendation:rec})}>Enviar mi recomendación</button></>}

function IndividualR3({state,onSend,busy}){const[d,setD]=useState({assignment:'',outcome:'',horizon:30});return <><div className="v2-step"><b>PASO 1 · DISEÑA TÚ</b><span>{V2_ROUNDS[3].individual}</span></div><div className="v2-grid sample">{state.packet.map(c=><CustomerCard key={c.id} c={c} mode="sample"/>)}</div><h3>¿Cómo asignarías la intervención?</h3><div className="v2-choice-row">{ASSIGNMENTS.map(([v,l])=><button className={d.assignment===v?'selected':''} key={v} onClick={()=>setD({...d,assignment:v})}>{l}</button>)}</div><div className="v2-form-grid"><label>Outcome<select value={d.outcome} onChange={e=>setD({...d,outcome:e.target.value})}><option value="">Selecciona…</option>{OUTCOMES.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Horizonte<select value={d.horizon} onChange={e=>setD({...d,horizon:Number(e.target.value)})}>{HORIZONS.map(x=><option value={x} key={x}>{x} días</option>)}</select></label></div><button className="v2-primary wide" disabled={busy||!d.assignment||!d.outcome} onClick={()=>onSend(d)}>Enviar mi diseño</button></>}

function IndividualR4({state,onSend,busy}){const initial=Object.fromEntries(state.packet.map(s=>[s.id,'observe']));const[choices,setChoices]=useState(initial);return <><div className="v2-step"><b>PASO 1 · PROPÓN TÚ</b><span>{V2_ROUNDS[4].individual}</span></div><div className="v2-segments">{state.packet.map(s=><article key={s.id}><div><h3>{s.name}</h3><small>{Number(s.audience).toLocaleString()} clientes · riesgo {s.risk}</small></div><div><b>{Number(s.effect)>0?'+':''}{s.effect} pp</b><small>IC [{s.ci_low}, {s.ci_high}]</small></div><select value={choices[s.id]||'observe'} onChange={e=>setChoices({...choices,[s.id]:e.target.value})}>{POLICY_ACTIONS.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></article>)}</div><button className="v2-primary wide" disabled={busy} onClick={()=>onSend({choices})}>Enviar mi propuesta</button></>}

function TeamProgress({state}){return <section className="v2-team-progress"><div className="v2-step"><b>PASO 2 · ESPERA AL EQUIPO</b><span>Cuando todos envíen, verán las propuestas y podrán decidir juntos.</span></div><div className="v2-team-roster">{state.team.roster.map(p=><div key={p.id} className={p.submitted?'ready':'waiting'}><span>{p.submitted?'✓':'…'}</span>{p.name}</div>)}</div><h2>{state.team.submitted}/{state.team.size} propuestas</h2></section>}

function ProposalSummary({state}){const r=state.game.round;return <section className="v2-proposals"><div className="v2-step"><b>PASO 2 · HABLEN</b><span>{V2_ROUNDS[r].team}</span></div><div className="v2-proposal-grid">{state.team_submissions.map(s=><article key={s.player_id}><b>{s.name}</b>{r===1&&<p>{(s.payload.selected||[]).join(', ')}</p>}{r===2&&<p>{RECOMMENDATIONS.find(x=>x[0]===s.payload.recommendation)?.[1]}</p>}{r===3&&<p>{ASSIGNMENTS.find(x=>x[0]===s.payload.assignment)?.[1]} · {OUTCOMES.find(x=>x[0]===s.payload.outcome)?.[1]} · {s.payload.horizon}d</p>}{r===4&&<p>{Object.entries(s.payload.choices||{}).map(([k,v])=>`${k}: ${POLICY_ACTIONS.find(x=>x[0]===v)?.[1]}`).join(' · ')}</p>}</article>)}</div></section>}

function TeamR1({state,onSend,busy}){const initial=useMemo(()=>[...new Set(state.team_submissions.flatMap(s=>s.payload.selected||[]))].slice(0,10),[state.game.round]);const[sel,setSel]=useState(initial);const toggle=id=>setSel(v=>v.includes(id)?v.filter(x=>x!==id):v.length<10?[...v,id]:v);return <><ProposalSummary state={state}/><div className="v2-step"><b>PASO 3 · DECIDAN JUNTOS</b><span>Cualquiera puede registrar la decisión. Seleccionen exactamente 10.</span></div><div className="v2-grid customers compact">{state.team_pool.map(c=><CustomerCard key={c.id} c={c} selected={sel.includes(c.id)} onClick={()=>toggle(c.id)}/>)}</div><div className="v2-sticky"><span>{sel.length}/10</span><button className="v2-primary" disabled={busy||sel.length!==10} onClick={()=>onSend({selected:sel})}>Bloquear decisión del equipo</button></div></>}

function TeamR2({state,onSend,busy}){const[rec,setRec]=useState('');return <><ProposalSummary state={state}/><div className="v2-step"><b>PASO 3 · DECIDAN JUNTOS</b><span>¿Qué harían con la estrategia?</span></div><div className="v2-choice-row">{RECOMMENDATIONS.map(([v,l])=><button className={rec===v?'selected':''} key={v} onClick={()=>setRec(v)}>{l}</button>)}</div><button className="v2-primary wide" disabled={busy||!rec} onClick={()=>onSend({recommendation:rec})}>Bloquear decisión del equipo</button></>}

function TeamR3({state,onSend,busy}){const[d,setD]=useState({assignment:'',outcome:'',horizon:30});return <><ProposalSummary state={state}/><div className="v2-step"><b>PASO 3 · DECIDAN JUNTOS</b><span>Construyan un único diseño antes de observar el resultado.</span></div><div className="v2-choice-row">{ASSIGNMENTS.map(([v,l])=><button className={d.assignment===v?'selected':''} key={v} onClick={()=>setD({...d,assignment:v})}>{l}</button>)}</div><div className="v2-form-grid"><label>Outcome<select value={d.outcome} onChange={e=>setD({...d,outcome:e.target.value})}><option value="">Selecciona…</option>{OUTCOMES.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Horizonte<select value={d.horizon} onChange={e=>setD({...d,horizon:Number(e.target.value)})}>{HORIZONS.map(x=><option value={x} key={x}>{x} días</option>)}</select></label></div><button className="v2-primary wide" disabled={busy||!d.assignment||!d.outcome} onClick={()=>onSend(d)}>Bloquear diseño del equipo</button></>}

function TeamR4({state,onSend,busy}){const segs=state.team_pool||[];const[choices,setChoices]=useState(Object.fromEntries(segs.map(s=>[s.id,'observe'])));const used=segs.filter(s=>choices[s.id]==='treat').reduce((a,s)=>a+Number(s.audience),0);function send(){onSend({treat:segs.filter(s=>choices[s.id]==='treat').map(s=>s.id),avoid:segs.filter(s=>choices[s.id]==='avoid').map(s=>s.id),observe:segs.filter(s=>choices[s.id]==='observe').map(s=>s.id)})}return <><ProposalSummary state={state}/><div className="v2-step"><b>PASO 3 · DECIDAN JUNTOS</b><span>Capacidad: {used.toLocaleString()} / 15.000.</span></div><div className="v2-segments">{segs.map(s=><article key={s.id}><div><h3>{s.name}</h3><small>{Number(s.audience).toLocaleString()} · riesgo {s.risk}</small></div><div><b>{Number(s.effect)>0?'+':''}{s.effect} pp</b><small>IC [{s.ci_low}, {s.ci_high}]</small></div><select value={choices[s.id]||'observe'} onChange={e=>setChoices({...choices,[s.id]:e.target.value})}>{POLICY_ACTIONS.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></article>)}</div><button className="v2-primary wide" disabled={busy||used>15000} onClick={send}>{used>15000?'Superan capacidad':'Bloquear política del equipo'}</button></>}

function Reveal({state}){const r=V2_ROUNDS[state.game.round],x=state.reveal||{};return <div className="v2-main"><MissionStrip round={state.game.round}/><section className="v2-reveal"><div className="v2-kicker">REVEAL · LO QUE ESTABA OCULTO</div><h1>{x.title||r.takeaway}</h1><div className="v2-concept">{x.concept||r.concept}</div>{state.game.round===1&&<><div className="v2-result"><b>Puntaje de decisión</b><strong>{state.team_decision?.result?.score??'—'}/100</strong><span>Impacto incremental elegido: {state.team_decision?.result?.uplift_pp_sum??'—'} pp acumulados</span></div><div className="v2-reveal-table">{(x.customers||[]).filter(c=>state.team_decision?.payload?.selected?.includes(c.id)).map(c=><div key={c.id}><b>{c.id}</b><span>score {pct(c.score)}</span><span>sin intervención {pct(c.p0)}</span><span>con intervención {pct(c.p1)}</span><strong>{Number(c.uplift_pp)>0?'+':''}{c.uplift_pp} pp</strong></div>)}</div></>}{state.game.round===2&&<div className="v2-metrics"><div><span>Diferencia cruda</span><strong>{x.crude_pp} pp</strong></div><div><span>Ajustada</span><strong>+{x.adjusted_pp} pp</strong></div><p><b>DAG:</b> {x.dag}</p><p>{x.overlap}</p></div>}{state.game.round===3&&<div className="v2-metrics"><div><span>Tratamiento</span><strong>{x.treatment_rate}%</strong></div><div><span>Control</span><strong>{x.control_rate}%</strong></div><div><span>ATE</span><strong>+{x.ate_pp} pp</strong><small>IC95% [{x.ci_low}, {x.ci_high}]</small></div><p>{x.lesson}</p></div>}{state.game.round===4&&<><div className="v2-alert error"><b>Stress test:</b> un outcome medido antes de la campaña muestra un “efecto” de +{x.placebo_pp} pp. La campaña no puede causar el pasado.</div><div className="v2-segments reveal">{(x.segments||[]).map(s=><article key={s.id}><b>{s.name}</b><span>{Number(s.effect_pp)>0?'+':''}{s.effect_pp} pp</span><small>IC [{s.ci_low}, {s.ci_high}] · {s.risk}</small></article>)}</div></>}<div className="v2-teach"><div className="v2-kicker">CONCEPTO NUEVO</div><h2>{r.concept}</h2><p>{r.takeaway}</p></div>{state.game.status==='finished'?<div className="v2-finished">Fin de la simulación. La pregunta final no es “¿qué predice el modelo?”, sino “¿qué cambiará si intervengo?”.</div>:<p className="v2-wait-note">Espera al facilitador para continuar.</p>}</section></div>}

function RoundPlay({state,refresh}){const[busy,setBusy]=useState(false),[err,setErr]=useState('');const round=state.game.round;async function send(action,payload){setBusy(true);setErr('');try{await invoke('v2-submit',{action,round,payload});await refresh()}catch(e){setErr(e.message)}finally{setBusy(false)}}return <div className="v2-main"><MissionStrip round={round}/><Hint text={state.hint} round={round}/>{err&&<div className="v2-alert error">{err}</div>}{!state.my_submission&&<>{round===1&&<IndividualR1 state={state} onSend={p=>send('individual',p)} busy={busy}/>} {round===2&&<IndividualR2 state={state} onSend={p=>send('individual',p)} busy={busy}/>} {round===3&&<IndividualR3 state={state} onSend={p=>send('individual',p)} busy={busy}/>} {round===4&&<IndividualR4 state={state} onSend={p=>send('individual',p)} busy={busy}/>}</>}{state.my_submission&&!state.team.all_submitted&&<TeamProgress state={state}/>} {state.team.all_submitted&&!state.team_decision&&<>{round===1&&<TeamR1 state={state} onSend={p=>send('team',p)} busy={busy}/>} {round===2&&<TeamR2 state={state} onSend={p=>send('team',p)} busy={busy}/>} {round===3&&<TeamR3 state={state} onSend={p=>send('team',p)} busy={busy}/>} {round===4&&<TeamR4 state={state} onSend={p=>send('team',p)} busy={busy}/>}</>} {state.team_decision&&<section className="v2-big-wait small"><Check size={44}/><h2>Decisión del equipo registrada</h2><p>Esperen el reveal. No hay nada más que hacer.</p></section>}</div>}

export default function V2Play(){const[joined,setJoined]=useState(Boolean(getPlayerToken()));const{state,error,refresh}=useV2State(joined);function exit(){clearPlayerSession();setJoined(false);location.reload()}if(!joined)return <Join onJoined={()=>setJoined(true)}/>;if(error&&!state)return <main className="v2-shell v2-center"><div className="v2-alert error">{error}</div><button className="v2-secondary" onClick={exit}>Volver a entrar</button></main>;if(!state)return <main className="v2-shell v2-center"><div className="v2-loader">Conectando…</div></main>;const waiting=['lobby','briefing','lesson'].includes(state.game.status);const reveal=['reveal','teaching','microcheck','finished'].includes(state.game.status);return <div className="v2-shell"><Header state={state} onExit={exit}/>{waiting&&<Lobby state={state}/>} {state.game.status==='round'&&<RoundPlay state={state} refresh={refresh}/>} {state.game.status==='paused'&&<div className="v2-main"><MissionStrip round={state.game.round}/><section className="v2-big-wait"><h2>Ronda pausada</h2><p>Conserven su discusión; el facilitador la reanudará.</p></section></div>} {state.game.status==='closed'&&<div className="v2-main"><MissionStrip round={state.game.round}/><section className="v2-big-wait"><h2>Decisiones cerradas</h2><p>Vuelvan la atención a la pantalla principal.</p></section></div>} {reveal&&<Reveal state={state}/>}<footer className="v2-footer"><span>{statusCopy(state.game.status)}</span><span>{state.player.team} · {state.player.name}</span></footer></div>}
