import React,{useEffect,useRef,useState}from'react'
import{CheckCircle2,Users}from'lucide-react'
import{invoke}from'../lib/api'
import{V2_ROUNDS,statusCopy}from'./content'

const jitter=n=>Math.round(n*(.9+Math.random()*.2))
export default function V2Wall(){
  const params=new URLSearchParams(location.search)
  const[code,setCode]=useState((params.get('game')||'').toUpperCase())
  const[data,setData]=useState(null),[err,setErr]=useState('')
  const[newIds,setNewIds]=useState(new Set()),seen=useRef(new Set())
  async function refresh(){if(!code)return;try{const x=await invoke('v2-wall-state',{game_code:code});const current=new Set((x.players||[]).map(p=>p.id));const fresh=[...current].filter(id=>!seen.current.has(id));if(fresh.length){setNewIds(new Set(fresh));setTimeout(()=>setNewIds(new Set()),1200)}seen.current=current;setData(x);setErr('')}catch(e){setErr(e.message)}}
  useEffect(()=>{if(!code)return;let stop=false,t;const loop=async()=>{await refresh();if(!stop)t=setTimeout(loop,jitter(1800))};loop();return()=>{stop=true;clearTimeout(t)}},[code])
  if(!code)return <main className="v2-shell v2-center"><section className="v2-join-card"><div className="v2-brand">DOS FUTUROS <span>V2 WALL</span></div><h1>¿Qué sesión quieres proyectar?</h1><label>Código<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="DF2-ABC123"/></label></section></main>
  if(err&&!data)return <main className="v2-shell v2-center"><div className="v2-alert error">{err}</div></main>
  if(!data)return <main className="v2-shell v2-center"><div className="v2-loader">Conectando…</div></main>
  const g=data.game,r=V2_ROUNDS[g.round];const lobby=['lobby','briefing','lesson'].includes(g.status)
  return <main className="v2-wall"><div className="v2-wall-top"><div><div className="v2-brand">DOS FUTUROS <span>V2</span></div><div className="v2-kicker">{lobby?'ÚNETE DESDE TU TELÉFONO':statusCopy(g.status)}</div></div><div className="v2-wall-code"><span>CÓDIGO DE SESIÓN</span><strong>{g.code}</strong></div></div>{lobby?<><div className="v2-wall-count"><strong>{data.humans}</strong><span>participantes conectados</span></div><div className="v2-wall-teams">{data.teams.map(t=>{const members=data.players.filter(p=>p.team_id===t.id);const full=t.humans>=3;return <section className={`v2-wall-team ${full?'ready':''}`} key={t.id}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2>{t.name}</h2>{full&&<CheckCircle2 size={22}/>}</div>{members.map(p=><div className={`v2-wall-player ${p.online?'':'offline'} ${newIds.has(p.id)?'new':''}`} key={p.id}><span>{p.name}</span><b>{p.online?'●':'○'}</b></div>)}{!members.length&&<div className="v2-wall-player offline">Esperando…</div>}<div className="v2-wall-progress"><i style={{width:`${Math.min(100,(t.humans/4)*100)}%`}}/></div><small>{t.humans}/4 {full?'· LISTO':'· entrando'}</small></section>})}</div>{data.humans>0&&data.teams.filter(t=>t.humans>0).every(t=>t.humans>=3)&&<div className="v2-wall-phase"><h1>✓ EQUIPOS LISTOS</h1><p>El facilitador puede iniciar la misión.</p></div>}</>:<><div className="v2-wall-phase"><div className="v2-kicker">RONDA {g.round} DE 4</div><h1>{r?.title}</h1><p>{r?.case}</p></div><div className="v2-wall-teams">{data.teams.filter(t=>t.humans>0).map(t=>{const progress=t.humans?Math.round((t.submitted/t.humans)*100):0;return <section className={`v2-wall-team ${t.decision?'ready':''}`} key={t.id}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2>{t.name}</h2>{t.decision&&<CheckCircle2 size={24}/>}</div><div className="v2-wall-count" style={{margin:'12px 0'}}><strong style={{fontSize:38}}>{t.decision?'✓':`${t.submitted}/${t.humans}`}</strong><span>{t.decision?'DECISIÓN LISTA':t.submitted>=t.humans?'DELIBERANDO':'propuestas individuales'}</span></div><div className="v2-wall-progress"><i style={{width:`${t.decision?100:progress}%`}}/></div></section>})}</div>{g.status==='reveal'&&<div className="v2-wall-phase"><h1>REVEAL</h1><p>{r?.concept}</p></div>}</>}</main>
}
