import React,{useEffect,useState}from'react'
import{DECISION_OPTIONS,EXPERIMENT_BASE}from'../causal-tools'

export function ExperimentCoverageTool({round,onEvidence}){
  const[n,setN]=useState(2000);const[assignment,setAssignment]=useState('random');const[outcome,setOutcome]=useState('');const[horizon,setHorizon]=useState('')
  if(round<3){
    useEffect(()=>onEvidence({summary:'Doble sombrero preparado: todavía no se ejecuta un RCT; define contra qué grupo compararías la intervención.',assumption:'Una diferencia sólo es causal si el comparador representa un contrafactual defendible.',decision:'No prometer causalidad experimental antes de definir la regla de asignación.',details:{prepared:true,round}}),[round])
    return <div className="tool-body"><div className="locked-tool"><b>🐢 Sombrero de Experimentos · se activa en ronda 3</b><p>Como el equipo tiene tres personas, Modelos cubrirá también esta responsabilidad. Por ahora pregunta: ¿contra qué grupo sería justa la comparación?</p></div></div>
  }
  const drift={200:.6,2000:0,20000:.1}[n]||0;const selectionBias=assignment==='random'?0:assignment==='model'?7.8:-4.9;const c=EXPERIMENT_BASE.controlRate,t=EXPERIMENT_BASE.treatmentRate+drift+selectionBias,diff=t-c;const se=Math.sqrt((t/100*(1-t/100))/(n/2)+(c/100*(1-c/100))/(n/2))*100;const lo=diff-1.96*se,hi=diff+1.96*se;const balance=assignment==='random'?{age:.3,mora:1.2}:assignment==='model'?{age:7.4,mora:28.0}:{age:5.6,mora:21.0};const causal=assignment==='random',estimateLabel=causal?'ATE estimado':'Diferencia observada'
  useEffect(()=>onEvidence({summary:`${assignment==='random'?'Azar':assignment==='model'?'Modelo':'Asesor'} · N=${n.toLocaleString()} · ${estimateLabel} ${diff.toFixed(1)} pp · IC95% [${lo.toFixed(1)}, ${hi.toFixed(1)}].`,assumption:causal?'La asignación aleatoria sostiene la comparabilidad en expectativa.':'La asignación depende de un criterio que puede volver incomparables los grupos; el intervalo no elimina sesgo de selección.',decision:outcome&&horizon?`Medir ${outcome} a ${horizon}.`:'Falta fijar outcome y horizonte antes de ejecutar.',details:{n,assignment,outcome,horizon,ate:causal?diff:null,observedDifference:diff,ci:[lo,hi],causal}}),[n,assignment,outcome,horizon,diff])
  return <div className="tool-body"><div className="notice notice-gold"><b>🦉 + 🐢 Doble sombrero</b><br/>Tu evidencia de Modelos sigue siendo independiente. Este módulo produce la pieza de Experimentos que falta en el equipo.</div><div className="experiment-controls"><label><b>Asignación</b><select className="select" value={assignment} onChange={e=>setAssignment(e.target.value)}><option value="advisor">Asesor</option><option value="model">Modelo</option><option value="random">Azar</option></select></label><label><b>N</b><select className="select" value={n} onChange={e=>setN(Number(e.target.value))}><option>200</option><option>2000</option><option>20000</option></select></label><label><b>Outcome</b><select className="select" value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="">Selecciona…</option>{DECISION_OPTIONS.outcome.map(x=><option key={x}>{x}</option>)}</select></label><label><b>Horizonte</b><select className="select" value={horizon} onChange={e=>setHorizon(e.target.value)}><option value="">Selecciona…</option>{DECISION_OPTIONS.horizon.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="experiment-result"><div><small>Tratamiento</small><b>{t.toFixed(1)}%</b></div><div><small>Control</small><b>{c.toFixed(1)}%</b></div><div><small>{estimateLabel}</small><b>{diff>=0?'+':''}{diff.toFixed(1)} pp</b></div><div><small>IC95%</small><b>[{lo.toFixed(1)}, {hi.toFixed(1)}]</b></div></div><div className="balance-panel"><b>Chequeo de balance simulado</b><span>Diferencia edad media: {balance.age.toFixed(1)} años</span><span>Diferencia mora alta: {balance.mora.toFixed(1)} pp</span></div><div className={`notice ${causal?'notice-green':'notice-gold'}`}>{causal?'Cambia N: la precisión aumenta con más información.':'Aumentar N no corrige una regla de asignación sesgada.'}</div></div>
}

const riskRank=x=>{const s=String(x||'').toLowerCase();return s.includes('high')||s.includes('alto')?3:s.includes('med')?2:1}
export function StrategyPolicyTool({state,onEvidence}){
  const segments=state.segments||[];const baseCapacity=Number(state.policy?.capacity||15000);const[capacity,setCapacity]=useState(baseCapacity);const[budget,setBudget]=useState(120000);const[tolerance,setTolerance]=useState(2);const[allocation,setAllocation]=useState({});useEffect(()=>setCapacity(baseCapacity),[baseCapacity]);const rows=segments.map(s=>{const n=Number(s.audience||0),effect=Number(s.effect||0),value=Number(s.value_per_result||0),cost=Number(s.unit_cost||0),unitNet=effect/100*value-cost;return{...s,n,value,cost,unitNet,fullNet:n*unitNet}});const chosen=rows.map(r=>({...r,allocated:Math.min(r.n,Math.max(0,Number(allocation[r.id]||0)))})).filter(r=>r.allocated>0);const selected=chosen.map(r=>r.id),used=chosen.reduce((a,r)=>a+r.allocated,0),spend=chosen.reduce((a,r)=>a+r.allocated*r.cost,0),net=chosen.reduce((a,r)=>a+r.allocated*r.unitNet,0);const riskViolation=chosen.some(r=>riskRank(r.risk)>tolerance);const valid=used<=capacity&&spend<=budget&&!riskViolation
  useEffect(()=>onEvidence({summary:selected.length?`${selected.length} segmentos · ${used.toLocaleString()} personas asignadas · valor neto ${Math.round(net).toLocaleString()}.`:'Política aún sin personas asignadas.',assumption:'Los CATE y sus intervalos son utilizables sólo si identificación, experimento y restricción son defendibles.',decision:valid&&selected.length?'Política factible bajo capacidad, presupuesto y tolerancia de riesgo.':'Revisar restricciones antes de recomendar despliegue.',details:{selected,allocation,used,spend,net,capacity,budget,tolerance,riskViolation,feasible:valid}}),[JSON.stringify(allocation),capacity,budget,tolerance])
  function allocate(id,max,value){setAllocation(a=>({...a,[id]:Math.min(max,Math.max(0,Number(value)||0))}))}
  return <div className="tool-body"><div className="notice"><b>🦁 Cierre de política</b><br/>Ésta es la segunda mitad de tu rol: la misma persona que definió la pregunta debe verificar que la acción final respete la restricción acordada.</div><div className="policy-controls-v7"><label><b>Capacidad máxima</b><input className="input" type="number" value={capacity} onChange={e=>setCapacity(Math.max(0,Number(e.target.value)||0))}/></label><label><b>Presupuesto</b><input className="input" type="number" value={budget} onChange={e=>setBudget(Math.max(0,Number(e.target.value)||0))}/></label><label><b>Tolerancia riesgo</b><select className="select" value={tolerance} onChange={e=>setTolerance(Number(e.target.value))}><option value="1">Baja</option><option value="2">Media</option><option value="3">Alta</option></select></label></div><div className="policy-table-v7"><b>Asignar</b><b>Segmento</b><b>CATE / IC95%</b><b>Personas disp.</b><b>Valor neto si total</b><b>Riesgo</b>{rows.map(r=><React.Fragment key={r.id}><input className="input" style={{minWidth:72}} type="number" min="0" max={r.n} step="100" value={allocation[r.id]||0} onChange={e=>allocate(r.id,r.n,e.target.value)}/><span>{r.name}</span><span>{Number(r.effect)>0?'+':''}{r.effect} pp · [{r.ci_low},{r.ci_high}]</span><span>{r.n.toLocaleString()}</span><span>{Math.round(r.fullNet).toLocaleString()}</span><span>{r.risk}</span></React.Fragment>)}</div><div className={`notice ${valid?'notice-green':'notice-red'}`}>Capacidad {used.toLocaleString()}/{capacity.toLocaleString()} · presupuesto {Math.round(spend).toLocaleString()}/{budget.toLocaleString()} · neto {Math.round(net).toLocaleString()}{riskViolation?' · riesgo excede tolerancia':''}</div></div>
}
