import React,{useEffect,useState}from'react'
import{Clock3,GraduationCap,Minus,Plus,ShieldCheck}from'lucide-react'
import{invoke}from'../lib/api'

export function ExpertAvailabilityPanel({round}){
  const[data,setData]=useState(null);const[busy,setBusy]=useState('');const[err,setErr]=useState('')
  async function refresh(){try{setData(await invoke('expert-market',{},'facilitator'));setErr('')}catch(e){setErr(e.message)}}
  useEffect(()=>{refresh();const i=setInterval(refresh,5000);return()=>clearInterval(i)},[round])
  async function setSlots(help_id,slots){setBusy(help_id);try{setData(await invoke('expert-market',{action:'set',help_id,slots},'facilitator'));setErr('')}catch(e){setErr(e.message)}finally{setBusy('')}}
  return <div className="card expert-admin"><div className="section-title" style={{marginTop:0}}><h3>Llamada al Capítulo · ronda {data?.round||round}</h3><p>El Game Master dirige y nunca está a la venta. Habilita aquí cuántas consultas reales pueden atender los tres facilitadores expertos durante esta ronda. La ayuda sólo puede usar conceptos ya explicados.</p></div><div className="expert-admin-grid">{(data?.experts||[]).map(x=>{const p=x.profile||{};const slots=Number(x.slots||0),used=Number(x.used||0);return <div className="expert-admin-card" key={x.help_id}><div className="expert-admin-head"><GraduationCap/><div><b>{x.title}</b><small>{p.rank}</small></div></div><p>{p.scope}</p><div className="expert-price-curve"><span>Precio según demanda</span><b>{(x.price_curve||[]).join(' → ')}</b></div><div className="slot-control"><button className="btn btn-ghost" disabled={busy===x.help_id||slots<=used} onClick={()=>setSlots(x.help_id,Math.max(used,slots-1))}><Minus size={14}/></button><div><strong>{slots}</strong><span>consultas habilitadas · {used} reservadas</span></div><button className="btn btn-ghost" disabled={busy===x.help_id||slots>=3} onClick={()=>setSlots(x.help_id,slots+1)}><Plus size={14}/></button></div><div className={`availability-status ${slots>used?'on':'off'}`}>{slots>used?<><ShieldCheck size={14}/> Hay un facilitador disponible</>:<><Clock3 size={14}/> Sin cupos disponibles</>}</div></div>})}</div><div className="notice">Sugerencia: máximo <b>3 consultas por ronda</b>, una por facilitador experto. Cada consulta dura 90 segundos y debe cerrar con una pregunta socrática, no con la respuesta del juego.</div>{err&&<div className="notice notice-red">Disponibilidad: {err}</div>}</div>
}
