import React,{useEffect,useMemo,useState}from'react'
import{Bot,BrainCircuit,CheckCircle2,Coins,GraduationCap,Lightbulb,LockKeyhole,Minus,Network,PackageCheck,Plus,ShoppingCart,TrendingUp,UserPlus,Wrench,X}from'lucide-react'
import{invoke}from'../lib/api'

const META={hint:{label:'Pistas',icon:Lightbulb},tool:{label:'Herramientas',icon:Wrench},talent:{label:'Talento disponible',icon:UserPlus},expert:{label:'Expertos humanos',icon:GraduationCap}}
const rarityStars={common:'★',rare:'★★',epic:'★★★',legendary:'★★★★'}
function HelpResult({p}){const r=p.result||{};return <div className="help-result"><div className="eyebrow">{r.title||'RESULTADO'}</div>{r.metrics&&<div className="help-metrics">{r.metrics.map((m,i)=><div key={i}><span>{m[0]}</span><b>{m[1]}</b></div>)}</div>}{r.edges&&<div className="dag-mini">{r.edges.map((e,i)=><span key={i}><Network size={14}/>{e}</span>)}</div>}{r.text&&<p>{r.text}</p>}{r.master&&<div className="expert-call"><GraduationCap size={18}/><b>{r.master}</b><span>{r.seconds||90}s</span></div>}</div>}
function Supply({h}){if(h.stock===null||h.stock===undefined)return <span className="stock-pill open">mercado abierto</span>;return <span className={`stock-pill ${h.remaining>0?'open':'sold'}`}>{h.remaining>0?`${h.remaining}/${h.stock} disponibles`:'AGOTADO'}</span>}

export function QuestMarket({state}){
  const[data,setData]=useState(null);const[busy,setBusy]=useState(false);const[err,setErr]=useState('');const[open,setOpen]=useState(false);const[cart,setCart]=useState({})
  async function refresh(){try{setData(await invoke('help-state'));setErr('')}catch(e){setErr(e.message)}}
  useEffect(()=>{if(state.game.phase!=='round')return;setCart({});refresh();const i=setInterval(refresh,3000);return()=>clearInterval(i)},[state.game.phase,state.game.round])
  const purchasesById=useMemo(()=>{const m={};for(const p of(data?.purchases||[]))m[p.help_id]=(m[p.help_id]||0)+1;return m},[data])
  const groups=useMemo(()=>Object.fromEntries(Object.keys(META).map(k=>[k,(data?.catalog||[]).filter(x=>x.category===k)])),[data])
  const catalogById=useMemo(()=>Object.fromEntries((data?.catalog||[]).map(x=>[x.id,x])),[data])
  const cartUnits=Object.values(cart).reduce((a,b)=>a+b,0)
  function maxQty(h){if(!h?.repeatable)return 1;if(h.remaining===null||h.remaining===undefined)return 4;return Math.max(0,Math.min(4,Number(h.remaining||0)))}
  function add(h){if(!h?.available)return;setCart(c=>({...c,[h.id]:Math.min(maxQty(h),(c[h.id]||0)+1)}))}
  function dec(id){setCart(c=>{const n=(c[id]||0)-1;const next={...c};if(n<=0)delete next[id];else next[id]=n;return next})}
  function clear(id){setCart(c=>{const next={...c};delete next[id];return next})}
  async function checkout(){const items=Object.entries(cart).map(([help_id,qty])=>({help_id,qty}));if(!items.length)return;if(!confirm(`Confirmar cesta de ${cartUnits} recurso${cartUnits===1?'':'s'}? El servidor aplicará el precio marginal real según la demanda en ese instante. La operación es todo-o-nada.`))return;setBusy(true);try{const r=await invoke('buy-help-batch',{items});setData(r.state);setCart({});alert(`Compra confirmada: ${r.units} recurso(s), inversión total ${r.total_cost}.`)}catch(e){alert(e.message);await refresh()}finally{setBusy(false)}}
  if(state.game.phase!=='round')return null
  const canPurchase=Boolean(data?.can_purchase)
  return <div className="quest-market"><div className="market-head"><div><div className="eyebrow">MERCADO DE RECURSOS</div><h2>La ayuda es una inversión escasa.</h2><p>El inventario es global por ronda. El primero compra más barato; cada unidad posterior puede subir de precio. Todos los hallazgos adquiridos quedan disponibles para el equipo.</p>{!canPurchase&&<div className="buyer-lock"><LockKeyhole size={15}/><span>Sólo el <b>Decision Lead</b> ejecuta la cesta y administra la bolsa. Los demás roles recomiendan qué adquirir.</span></div>}</div><div className="market-score"><Coins/><span>Bolsa de inversión</span><strong>{data?.investment_balance??0}</strong><small>Inversión acumulada −{data?.help_cost||0}</small></div></div><button className="btn quest-market-toggle" onClick={()=>setOpen(v=>!v)}><ShoppingCart size={17}/>{open?'Cerrar mercado':'Explorar mercado y disponibilidad'}</button>{open&&<div className="market-body">{Object.entries(META).map(([cat,meta])=>{const Icon=meta.icon;return <section key={cat}><div className="market-category"><Icon size={19}/><h3>{meta.label}</h3></div><div className="market-grid">{(groups[cat]||[]).map(h=>{const owned=purchasesById[h.id]||0;const inCart=cart[h.id]||0;const already=!h.repeatable&&owned>0;const full=inCart>=maxQty(h);const insufficient=(data?.investment_balance??0)<Number(h.next_cost||0);const disabled=busy||already||!h.available||insufficient||!canPurchase||full;return <div className={`help-card rarity-${h.rarity} ${already?'bought':''} ${!h.available?'sold-out':''}`} key={h.id}><div className="help-card-top"><span>{rarityStars[h.rarity]||'★'} {h.rarity}</span><b><Coins size={14}/>{h.next_cost}</b></div><div className="market-demand"><Supply h={h}/>{Number(h.sold_count||0)>0&&<span><TrendingUp size={12}/> demanda {h.sold_count}</span>}</div><h4>{h.title}</h4>{h.profile?.max_role&&<div className="expert-rank"><b>{h.profile.rank}</b><small>→ {h.profile.max_role}</small></div>}<p>{h.description}</p>{h.profile?.scope&&<small className="expert-scope">{h.profile.scope}</small>}<button className="btn" disabled={disabled} onClick={()=>add(h)}>{already?<><CheckCircle2 size={16}/> Utilizada</>:!h.available?'Agotado':insufficient?'Sin capital':inCart>0?<><Plus size={15}/> Añadir otra · próxima desde {h.next_cost}</>:<><ShoppingCart size={15}/> Añadir a cesta · desde {h.next_cost}</>}</button>{(owned>0||inCart>0)&&<small className="owned-count">Equipo: {owned} adquirida(s){inCart>0?` · cesta ${inCart}`:''}</small>}</div>})}</div></section>})}
      <div className={`market-cart ${cartUnits?'active':''}`}><div className="market-cart-head"><div><div className="eyebrow">CESTA DE INVERSIÓN</div><h3>{cartUnits?`${cartUnits} recurso${cartUnits===1?'':'s'} por confirmar`:'Cesta vacía'}</h3></div><PackageCheck/></div>{cartUnits>0&&<><div className="market-cart-lines">{Object.entries(cart).map(([id,qty])=>{const h=catalogById[id];return <div className="market-cart-line" key={id}><div><b>{h?.title||id}</b><small>precio actual de la próxima unidad: {h?.next_cost??'—'} · el total final se calcula atómicamente</small></div><div className="cart-qty"><button onClick={()=>dec(id)}><Minus size={13}/></button><strong>{qty}</strong>{h?.repeatable&&qty<maxQty(h)?<button onClick={()=>add(h)}><Plus size={13}/></button>:<button onClick={()=>clear(id)}><X size={13}/></button>}</div></div>})}</div><button className="btn btn-primary basket-checkout" disabled={!canPurchase||busy} onClick={checkout}><PackageCheck size={17}/>{busy?'Reservando inventario…':'Comprar cesta · todo o nada'}</button><small className="basket-note">El checkout bloquea inventario y precio marginal en servidor. Si un recurso se agotó o la bolsa no alcanza, no se compra nada de la cesta.</small></>}</div>
      <div className="ai-expert-proposal"><div className="ai-orb"><BrainCircuit/></div><div><div className="eyebrow">HERRAMIENTA ADICIONAL POSIBLE</div><h3>Experto IA del Juego · bloqueado</h3><p>Puede habilitarse por API con contexto estrictamente limitado a la ronda, conceptos ya desbloqueados y estado público del equipo. No tendría acceso al repositorio, secretos, ground truth futuro ni herramientas externas.</p><div className="ai-guardrails"><span><Bot size={13}/> 2 consultas/equipo/ronda</span><span>respuestas socráticas</span><span>sin revelar solución</span><span>conocimiento por ronda</span></div></div><LockKeyhole/></div><div className="purchased-panel"><h3>Inventario compartido del equipo</h3>{!(data?.purchases||[]).length?<p>Aún no han invertido. Esperar también es una decisión estratégica.</p>:(data.purchases||[]).map(p=><HelpResult key={p.id} p={p}/>)}</div>{err&&<div className="notice notice-red">Mercado: {err}</div>}</div>}</div>
}
