import React,{useMemo,useState} from 'react'
import {ROLE_TASKS,ROLE_TOOLS,TOOL_PRACTICE} from '../learning'
import {QuestMarket} from './QuestMarket'
import {RoleReveal} from './RoleReveal'
import {TeamContribution} from './TeamContribution'

function Bar({label,value,max=100,kind='blue',suffix='%'}){const width=Math.max(2,Math.min(100,100*Math.abs(Number(value||0))/Math.max(1,max)));return <div className="mini-bar-row"><div className="mini-bar-label"><span>{label}</span><b>{Number(value)>0&&suffix===' pp'?'+':''}{value}{suffix}</b></div><div className="mini-bar-track"><i className={kind} style={{width:`${width}%`}}/></div></div>}

function DecisionCanvas({round}){
  const presets={1:{population:'Clientes elegibles',treatment:'Intervención comercial',outcome:'Conversión a 30 días',horizon:'30 días'},2:{population:'Clientes comparables antes de la llamada',treatment:'Llamada de cobranza',outcome:'Pago',horizon:'30 días'},3:{population:'20.000 clientes elegibles',treatment:'Intervención',outcome:'Pago',horizon:'30 días'},4:{population:'Segmentos elegibles',treatment:'Intervenir',outcome:'Resultado incremental',horizon:'30 días'}}
  const p=presets[round]
  return <div className="tool-body"><div className="decision-flow"><div><small>1</small><b>Población</b><span>{p.population}</span></div><em>→</em><div><small>2</small><b>Intervención</b><span>{p.treatment}</span></div><em>→</em><div><small>3</small><b>Resultado</b><span>{p.outcome}</span></div><em>→</em><div><small>4</small><b>Horizonte</b><span>{p.horizon}</span></div></div><div className="notice notice-gold">Pregunta causal: ¿qué cambiaría en <b>{p.outcome}</b> si aplicamos <b>{p.treatment}</b> frente a no aplicarla en la misma población?</div></div>
}

function ModelExplorer({round}){
  const[mode,setMode]=useState('probabilidad')
  if(round===1){const rows=TOOL_PRACTICE.model[1];return <div className="tool-body"><div className="fac-toolbar"><button className={`btn ${mode==='probabilidad'?'btn-primary':''}`} onClick={()=>setMode('probabilidad')}>Probabilidad</button><button className={`btn ${mode==='impacto'?'btn-primary':''}`} onClick={()=>setMode('impacto')}>Otro futuro · ejemplo</button></div><div className="visual-chart">{rows.map(r=><div className="visual-group" key={r.name}><h4>{r.name}</h4>{mode==='probabilidad'?<Bar label="Probabilidad estimada" value={r.propensity}/>:<><Bar label="Sin intervención" value={r.p0} kind="muted"/><Bar label="Con intervención" value={r.p1} kind="cyan"/><div className="delta-chip">Cambio incremental: +{r.p1-r.p0} pp</div></>}</div>)}</div><div className="notice">Ejemplo de práctica. La probabilidad de convertir no es lo mismo que cuánto cambia una persona por la intervención.</div></div>}
  if(round===2){const x=TOOL_PRACTICE.model[2];return <div className="tool-body"><div className="visual-chart"><div className="visual-group"><h4>Cómo cambia la historia al ajustar</h4><Bar label="Comparación cruda" value={x.crude} max={15} kind="red" suffix=" pp"/><Bar label="Regresión ajustada" value={x.regression} max={15} kind="green" suffix=" pp"/><Bar label="Ponderación IPW" value={x.ipw} max={15} kind="cyan" suffix=" pp"/></div></div><div className="notice">No elijas el método “más bonito”: explica por qué ajustar por diferencias previas cambia la comparación.</div></div>}
  if(round===3)return <div className="tool-body"><div className="compare-panels"><div><b>Puntaje predictivo</b><span>Pronostica quién tendrá el resultado.</span></div><div><b>Asignación aleatoria</b><span>Ayuda a estimar cuánto cambia por intervenir.</span></div></div><div className="notice">El modelo puede ayudar a segmentar, pero no reemplaza un diseño experimental.</div></div>
  const rows=TOOL_PRACTICE.model[4];return <div className="tool-body"><div className="visual-chart">{rows.map(r=><div className="visual-group" key={r.name}><h4>{r.name}</h4><Bar label="Probabilidad base" value={r.propensity}/><Bar label="Impacto incremental" value={r.uplift} max={20} kind="green" suffix=" pp"/></div>)}</div><div className="notice">La Lente de Impacto Incremental ya está disponible: prioriza cambio causado, no sólo probabilidad base.</div></div>
}

function CausalWarmup(){return <div className="tool-body"><div className="locked-tool"><b>Tu herramienta avanzada todavía no está desbloqueada.</b><p>En esta ronda tu aporte es formular el contrafactual: ¿qué habría pasado con estos mismos clientes si no hubiéramos intervenido?</p></div><div className="notice">En la ronda 2 aprenderás grafo causal (DAG) y confusión; ahí aparecerán tus dos poderes avanzados.</div></div>}

function DagLab(){const[choice,setChoice]=useState('');const correct=choice==='Mora previa';return <div className="tool-body"><div className="dag-visual"><div className="dag-node prior">Mora previa</div><div className="dag-arrow a1">↓</div><div className="dag-node treatment">Llamada</div><div className="dag-arrow a2">→</div><div className="dag-node outcome">Pago</div><div className="dag-side">Mora previa → Pago</div></div><label className="form-row"><b>¿Qué variable hace peligrosa la comparación?</b><select className="select" value={choice} onChange={e=>setChoice(e.target.value)}><option value="">Selecciona…</option><option>Mora previa</option><option>Nombre</option><option>Clic posterior</option></select></label>{choice&&<div className={`notice ${correct?'notice-green':'notice-red'}`}>{correct?'Correcto: existe antes y afecta tanto la llamada como el pago.':'Revisa temporalidad: busca una variable previa que afecte ambos lados.'}</div>}<div className="method-chips"><span>Regresión ajustada</span><span>Emparejamiento</span><span>Ponderación IPW</span></div></div>}

function ExperimentWarmup(){return <div className="tool-body"><div className="locked-tool"><b>Escudo de Aleatorización y Medidor de Efecto Promedio se desbloquean en la ronda 3.</b><p>Mientras tanto, ayuda preguntando: “¿contra qué grupo estamos comparando y por qué esa comparación sería justa?”</p></div></div>}

function ExperimentLab(){const[n,setN]=useState(TOOL_PRACTICE.experiment.n);const[t,setT]=useState(TOOL_PRACTICE.experiment.treatmentRate);const[c,setC]=useState(TOOL_PRACTICE.experiment.controlRate);const diff=t-c;const se=Math.sqrt((t/100*(1-t/100))/(n/2)+(c/100*(1-c/100))/(n/2))*100;const lo=diff-1.96*se,hi=diff+1.96*se;return <div className="tool-body"><div className="grid grid-3"><label className="form-row"><b>N</b><input className="input" type="number" value={n} onChange={e=>setN(Math.max(100,Number(e.target.value)||100))}/></label><label className="form-row"><b>Tratamiento %</b><input className="input" type="number" value={t} onChange={e=>setT(Number(e.target.value)||0)}/></label><label className="form-row"><b>Control %</b><input className="input" type="number" value={c} onChange={e=>setC(Number(e.target.value)||0)}/></label></div><div className="visual-chart"><div className="visual-group"><h4>Comparación experimental</h4><Bar label="Tratamiento" value={t} kind="green"/><Bar label="Control" value={c} kind="muted"/><div className="delta-chip">Efecto promedio (ATE): {diff>=0?'+':''}{diff.toFixed(1)} pp</div><div className="ci-strip"><span style={{left:`${Math.max(0,Math.min(100,50+lo*3))}%`}}/><i style={{left:`${Math.max(0,Math.min(100,50+diff*3))}%`}}/><span style={{left:`${Math.max(0,Math.min(100,50+hi*3))}%`}}/></div><small>IC 95% aprox. [{lo.toFixed(1)}, {hi.toFixed(1)}] pp</small></div></div><div className="notice">Cambia N y las tasas para ver cómo cambian magnitud e incertidumbre.</div></div>}

function RiskWarmup(){return <div className="tool-body"><div className="risk-checklist"><div><b>1</b><span>¿Podemos desperdiciar presupuesto?</span></div><div><b>2</b><span>¿Algún grupo puede salir perjudicado?</span></div><div><b>3</b><span>¿La evidencia alcanza para una decisión irreversible?</span></div></div><div className="notice">Tu Escudo de Riesgo funciona desde el inicio. La Forja de Valor se desbloquea en la ronda 4, cuando aprendamos a convertir efecto en política.</div></div>}

function PolicySimulator(){const[audience,setAudience]=useState(TOOL_PRACTICE.policy.audience);const[effect,setEffect]=useState(TOOL_PRACTICE.policy.effectPP);const[value,setValue]=useState(TOOL_PRACTICE.policy.value);const[cost,setCost]=useState(TOOL_PRACTICE.policy.cost);const incremental=audience*effect/100;const net=incremental*value-audience*cost;const gross=incremental*value;const totalCost=audience*cost;return <div className="tool-body"><div className="grid grid-2"><label className="form-row"><b>Personas</b><input className="input" type="number" value={audience} onChange={e=>setAudience(Number(e.target.value)||0)}/></label><label className="form-row"><b>Efecto (pp)</b><input className="input" type="number" value={effect} onChange={e=>setEffect(Number(e.target.value)||0)}/></label><label className="form-row"><b>Valor por resultado</b><input className="input" type="number" value={value} onChange={e=>setValue(Number(e.target.value)||0)}/></label><label className="form-row"><b>Costo por intervención</b><input className="input" type="number" value={cost} onChange={e=>setCost(Number(e.target.value)||0)}/></label></div><div className="visual-chart"><div className="visual-group"><h4>Valor de la política</h4><Bar label="Valor bruto" value={gross} max={Math.max(gross,totalCost,1)} kind="green" suffix=""/><Bar label="Costo total" value={totalCost} max={Math.max(gross,totalCost,1)} kind="red" suffix=""/><div className={`delta-chip ${net<0?'negative':''}`}>Valor neto simplificado: {net.toLocaleString()}</div><small>{incremental.toFixed(0)} resultados incrementales esperados.</small></div></div><div className="notice">La Forja de Valor combina efecto, volumen y costo; el Escudo de Riesgo recuerda que valor esperado no es el único criterio.</div></div>}

export function RoleLab({state}){const role=state.player.role_code;const meta=ROLE_TOOLS[role];const round=state.game.round;const Body=useMemo(()=>{if(role==='business')return DecisionCanvas;if(role==='data')return ModelExplorer;if(role==='context')return round>=2?DagLab:CausalWarmup;if(role==='integrator')return round>=3?ExperimentLab:ExperimentWarmup;return round>=4?PolicySimulator:RiskWarmup},[role,round]);return <><RoleReveal state={state} phase="round"/><div className="tool-card" style={{borderColor:meta.color}}><div className="tool-head"><div><div className="eyebrow">TU APORTE · {meta.label}</div><h3>{meta.tool}</h3><p>{meta.purpose}</p></div><div className="pill">Ronda {round}</div></div><div className="notice" style={{marginBottom:14}}><b>Tu misión en esta ronda:</b> {ROLE_TASKS[round]?.[role]}</div>{state.role_card&&<div className="role-intel"><b>Dato exclusivo de tu rol</b><p>{state.role_card}</p></div>}<Body round={round}/><div className="tool-share">📣 Usa la herramienta y luego registra un hallazgo estructurado. El rol aporta evidencia; no toma la decisión solo.</div></div><TeamContribution state={state}/><QuestMarket state={state}/></>}
