import React,{useEffect,useMemo,useState}from'react'
import{CheckCircle2,Lock,Users}from'lucide-react'
import{CORE_ROLE_CODES,ROLE_ARCHETYPES}from'../codex'
import{ROUND_COPY,MICROCHECKS}from'../content'
import{LESSONS}from'../learning'
import{GAME_MISSION,ROLE_ACTIONS,TRANSFER_CHECKS}from'../onboarding'
import{DECISION_RULE,ROLE_ROUND_BRIEFS,roleRoundBrief}from'../role-interdependence'
import{RoleReveal}from'./RoleReveal'
import{RoleLab}from'./RoleLab'

const SEGMENTS=[
  {id:'digital',name:'Jóvenes digitales',audience:7000,effect:13.5,ci_low:9,ci_high:18,value_per_result:120,unit_cost:4,risk:'Bajo'},
  {id:'middle',name:'Ingreso medio',audience:8000,effect:9,ci_low:5,ci_high:13,value_per_result:110,unit_cost:5,risk:'Medio'},
  {id:'traditional',name:'Tradicionales',audience:5000,effect:3,ci_low:-2,ci_high:8,value_per_result:90,unit_cost:6,risk:'Medio'},
  {id:'wealth',name:'Patrimonio alto',audience:2500,effect:1,ci_low:-3,ci_high:4,value_per_result:180,unit_cost:9,risk:'Bajo'},
  {id:'arrears',name:'Mora alta',audience:4000,effect:-5,ci_low:-9,ci_high:-1,value_per_result:80,unit_cost:8,risk:'Alto'}
]
const PREVIEW_CUSTOMERS=Array.from({length:24},(_,i)=>({id:`C${String(i+1).padStart(2,'0')}`,name:`Cliente ${String(i+1).padStart(2,'0')}`,segment:['Digital','Mixto','Tradicional'][i%3],score:.94-i*.019+(i%4)*.006}))
const PHASES=[['brief','Escenario'],['roles','4 roles'],['tools','Herramientas'],['table','Mesa'],['decision','Decisión'],['reveal','Reveal + cierre']]

function MissionPreview(){return <div className="card card-accent"><div className="eyebrow">LO PRIMERO QUE LEE CADA PARTICIPANTE</div><h2>{GAME_MISSION.title}</h2><p style={{fontSize:18}}>{GAME_MISSION.objective}</p><div className="grid grid-2" style={{marginTop:14}}><div className="card"><div className="eyebrow">LOS DOS FUTUROS</div><h3>{GAME_MISSION.future1}</h3><h3>{GAME_MISSION.future0}</h3><p>Sólo se observa uno. El equipo construye evidencia sobre el futuro que falta.</p></div><div className="card"><div className="eyebrow">CÓMO SE JUEGA</div><p><b>{GAME_MISSION.teamwork}</b></p><ol>{GAME_MISSION.loop.map(x=><li key={x}>{x}</li>)}</ol></div></div></div>}

function DiagnosticPreview(){return <div className="card"><div className="eyebrow">DIAGNÓSTICO INDIVIDUAL · FUERA DEL JUEGO</div><h2>Esto se ve una sola vez antes de R1</h2><div className="notice notice-gold">No da puntos, no es una ronda y no se comparte con el equipo.</div>{TRANSFER_CHECKS.pre.map(([id,q,opts],i)=><div className="transfer-question" key={id}><h3>{i+1}. {q}</h3>{opts.map(([v,l])=><label className="choice" key={v}><input type="radio" disabled name={`preview-${id}`}/>{l}</label>)}</div>)}</div>}

function CommonBrief({round}){const copy=ROUND_COPY[round],lesson=LESSONS[round];return <><div className="card card-accent"><div className="eyebrow">LO COMÚN · LO VEN LOS 4</div><h2>{copy.title}</h2><p><b>Misión del equipo:</b> {copy.mission}</p><div className="notice"><b>Regla de esta sala:</b> nadie bloquea la decisión antes de que las cuatro responsabilidades hayan compartido evidencia.</div></div><div className="card" style={{marginTop:14}}><div className="eyebrow">MINI-CLASE COMÚN · {lesson.minutes} MIN</div><h3>{lesson.title}</h3><p>{lesson.objective}</p><div className="formula">{lesson.formula}</div><div className="method-chips">{lesson.methods.map(x=><span key={x}>{x}</span>)}</div></div></>}

function RoleMap({round,onOpen}){return <div><div className="section-title"><div><div className="eyebrow">ASIMETRÍA DE INFORMACIÓN</div><h3>Cada persona sabe algo que las otras no reciben en su pantalla</h3></div></div><div className="grid grid-2">{CORE_ROLE_CODES.map(role=>{const m=ROLE_ARCHETYPES[role],a=ROLE_ACTIONS[role],b=roleRoundBrief(round,role);return <article className="card" key={role} style={{borderColor:m.accent}}><div className="eyebrow">{m.emoji} {m.label}</div><h3>En R{round}, ¿para qué sirve?</h3><p><b>Puede:</b> {a.can}</p><div className="notice notice-gold"><b>Información privada:</b><br/>{b.private}</div><p><b>Necesita preguntar al equipo:</b> {b.ask}</p><p><b>Entrega obligatoria:</b> {b.deliver}</p><p className="muted-copy"><b>No puede cerrar solo:</b> {a.cannot}</p><button className="btn" onClick={()=>onOpen(role)}>Abrir exactamente esta perspectiva</button></article>})}</div></div>}

function fakeState(round,role){const brief=roleRoundBrief(round,role);return{
  player:{id:`preview-${role}`,team_id:'preview-team',role_code:role,display_name:ROLE_ARCHETYPES[role].label},
  game:{round,status:'round',phase:'round'},teams:[],
  team_roster:CORE_ROLE_CODES.map((code,i)=>({id:`preview-${i}`,display_name:ROLE_ARCHETYPES[code].label,role_code:code})),
  segments:SEGMENTS,policy:{capacity:15000},role_card:brief?.private||null,locked:false
}}

function ToolPerspective({round,role,onRole}){const state=useMemo(()=>fakeState(round,role),[round,role]);return <><div className="fac-toolbar" style={{marginBottom:12,flexWrap:'wrap'}}>{CORE_ROLE_CODES.map(code=>{const m=ROLE_ARCHETYPES[code];return <button className={`btn ${role===code?'btn-primary':''}`} key={code} onClick={()=>onRole(code)}>{m.emoji} {m.label}</button>})}</div><div className="notice notice-green"><b>Modo profesor:</b> ésta es la herramienta real del participante, pero compartir evidencia, mercado y escrituras al backend están desactivados.</div><RoleReveal state={state} phase="lesson"/><RoleLab key={`${round}-${role}`} state={state} preview/></>}

function EvidenceTable({round,shared,onToggle}){return <><div className="card card-accent"><div className="eyebrow">MESA DE EVIDENCIA SIMULADA</div><h2>La decisión no existe hasta que las cuatro piezas llegan a la mesa</h2><p>{DECISION_RULE.requirement}</p></div><div className="grid grid-2" style={{marginTop:14}}>{CORE_ROLE_CODES.map(role=>{const m=ROLE_ARCHETYPES[role],b=ROLE_ROUND_BRIEFS[round][role];return <article className={`card ${shared[role]?'card-accent':''}`} key={role}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><b>{m.emoji} {m.label}</b>{shared[role]&&<CheckCircle2 size={18}/>}</div><p>{b.deliver}</p><button className="btn" onClick={()=>onToggle(role)}>{shared[role]?'Quitar evidencia de la mesa':'Simular: compartir evidencia'}</button></article>})}</div></>}

function DecisionPreview({round,shared}){const all=CORE_ROLE_CODES.every(r=>shared[r]);return <div className="card" style={{marginTop:14}}><div className="eyebrow">DECISIÓN DEL EQUIPO</div><h2>{all?'4/4 evidencias: 🦁 puede bloquear':'Bloqueada: faltan aportes del equipo'}</h2><p><b>{DECISION_RULE.label}</b> El servidor también verificará la cobertura; no es sólo una instrucción escrita.</p>{round===1&&<div className="customer-grid" style={{marginTop:14}}>{PREVIEW_CUSTOMERS.map(c=><div className="customer" key={c.id}><h4>{c.name}</h4><div className="seg">{c.segment}</div><div className="score-badge">{Math.round(c.score*100)}% <small>score</small></div></div>)}</div>}{round===2&&<div className="grid grid-3"><div className="metric"><span>Llamados</span><strong>20%</strong><small>pago</small></div><div className="metric"><span>No llamados</span><strong>35%</strong><small>pago</small></div><div className="notice notice-gold">La pantalla pide recomendar cancelar, mantener o rediseñar; la respuesta debe usar DAG + ajuste/overlap + juicio de diseño.</div></div>}{round===3&&<div className="notice notice-gold">La decisión fija <b>asignación + outcome + horizonte</b>. La evidencia de Experimentos aporta N/IC/MDE; Modelos y Causalidad impiden que “más datos” se confunda con “menos sesgo”.</div>}{round===4&&<div>{SEGMENTS.map(s=><div className="policy-row-v6" key={s.id}><div><b>{s.name}</b><small>{s.audience.toLocaleString()} clientes</small></div><div><b>{s.effect>0?'+':''}{s.effect} pp</b><small>IC95% [{s.ci_low},{s.ci_high}]</small></div><div><b>{s.risk}</b><small>riesgo</small></div><select className="select" disabled><option>Más evidencia</option></select></div>)}</div>}<button className="btn btn-primary" style={{marginTop:14}} disabled={!all}><Lock size={15}/> {all?'Simular bloqueo por 🦁':'Esperando 4/4 evidencias'}</button></div>}

function RevealPreview({round}){const copy=ROUND_COPY[round],q=MICROCHECKS[round];return <><div className="card card-accent"><div className="eyebrow">REVEAL / DEBRIEF · LO VE TODO EL EQUIPO</div><h2>{copy.teaching.title}</h2><p style={{fontSize:18}}>{copy.teaching.body}</p></div><div className="card" style={{marginTop:14}}><div className="eyebrow">MICROCHECK INDIVIDUAL · NO DA PUNTOS</div><h3>{q.prompt}</h3>{q.options.map(o=><label className="choice" key={o}><input type="radio" disabled/>{o}</label>)}</div></>}

export function TeamSimulator(){const[screen,setScreen]=useState('mission');const[round,setRound]=useState(1);const[phase,setPhase]=useState('brief');const[role,setRole]=useState('business');const[shared,setShared]=useState(Object.fromEntries(CORE_ROLE_CODES.map(r=>[r,false])));useEffect(()=>setShared(Object.fromEntries(CORE_ROLE_CODES.map(r=>[r,false]))),[round]);function openRound(r){setRound(r);setScreen('round');setPhase('brief')}function openRole(r){setRole(r);setPhase('tools')}function toggle(r){setShared(s=>({...s,[r]:!s[r]}))}return <div className="team-simulator"><div className="notice notice-green"><b>Ensayo de equipo completo · sin backend.</b> Aquí puedes recorrer tú solo lo que leerían cuatro participantes distintos. No crea jugadores, no compra ayudas y no altera la partida real.</div><div className="fac-toolbar" style={{margin:'14px 0',flexWrap:'wrap'}}><button className={`btn ${screen==='mission'?'btn-primary':''}`} onClick={()=>setScreen('mission')}>Misión</button><button className={`btn ${screen==='diagnostic'?'btn-primary':''}`} onClick={()=>setScreen('diagnostic')}>Diagnóstico</button>{[1,2,3,4].map(r=><button className={`btn ${screen==='round'&&round===r?'btn-primary':''}`} key={r} onClick={()=>openRound(r)}>Ronda {r}</button>)}</div>{screen==='mission'&&<MissionPreview/>}{screen==='diagnostic'&&<DiagnosticPreview/>}{screen==='round'&&<><div className="fac-toolbar" style={{marginBottom:14,flexWrap:'wrap'}}>{PHASES.map(([id,label])=><button className={`btn ${phase===id?'btn-primary':''}`} key={id} onClick={()=>setPhase(id)}>{label}</button>)}</div>{phase==='brief'&&<CommonBrief round={round}/>} {phase==='roles'&&<RoleMap round={round} onOpen={openRole}/>} {phase==='tools'&&<ToolPerspective round={round} role={role} onRole={setRole}/>} {phase==='table'&&<EvidenceTable round={round} shared={shared} onToggle={toggle}/>} {phase==='decision'&&<><EvidenceTable round={round} shared={shared} onToggle={toggle}/><DecisionPreview round={round} shared={shared}/></>} {phase==='reveal'&&<RevealPreview round={round}/>}</>}</div>}
