import React,{useEffect,useMemo,useState}from'react'
import{ArrowLeft,FlaskConical,Plus,RotateCcw}from'lucide-react'
import{Layout}from'../components/Layout'
import{RoleReveal}from'../components/RoleReveal'
import{StrategyPolicyTool}from'../components/AdaptiveCoverageTools'
import{DECISION_OPTIONS,DAG_SCENARIOS,ESTIMATORS,EXPERIMENT_BASE,TOOL_GUIDE,UPLIFT_CLIENTS}from'../causal-tools'
import{ROLE_TASKS,ROLE_TOOLS,TOOL_PRACTICE}from'../learning'
import{getFacilitatorToken}from'../lib/api'

const ROLES=[
  ['business','🦁','Estrategia y Política'],
  ['data','🦉','Modelos'],
  ['context','🐈‍⬛','Causalidad'],
  ['integrator','🐢','Experimentos'],
  ['risk','🦅','Copiloto opcional']
]
const SAMPLE_SEGMENTS=[
  {id:'s1',name:'Alta oportunidad',audience:4200,effect:12.4,ci_low:8.2,ci_high:16.6,value_per_result:120,unit_cost:7,risk:'Baja'},
  {id:'s2',name:'Oportunidad media',audience:6000,effect:6.1,ci_low:2.0,ci_high:10.2,value_per_result:95,unit_cost:6,risk:'Media'},
  {id:'s3',name:'Incierto',audience:5000,effect:1.4,ci_low:-2.5,ci_high:5.3,value_per_result:90,unit_cost:5,risk:'Media'},
  {id:'s4',name:'Posible daño',audience:3100,effect:-4.8,ci_low:-8.5,ci_high:-1.1,value_per_result:110,unit_cost:7,risk:'Alta'},
  {id:'s5',name:'Nicho rentable',audience:1800,effect:9.0,ci_low:2.8,ci_high:15.2,value_per_result:150,unit_cost:10,risk:'Baja'}
]

function Evidence({value}){if(!value)return <div className="notice">Interactúa con la herramienta para producir evidencia.</div>;return <div className="evidence-preview"><b>Evidencia generada en sandbox</b><span>{value.summary}</span><small><strong>Supuesto:</strong> {value.assumption}</small><small><strong>Qué permite decidir:</strong> {value.decision}</small></div>}

function DecisionSandbox({round,onEvidence}){
  const[d,setD]=useState({population:'',treatment:'',comparator:'',outcome:'',horizon:'',estimand:'',constraint:'',constraintValue:''})
  useEffect(()=>{setD({population:'',treatment:'',comparator:'',outcome:'',horizon:'',estimand:'',constraint:'',constraintValue:''})},[round])
  const needsValue=d.constraint&&d.constraint!=='Sin restricción explícita'
  const complete=['population','treatment','comparator','outcome','horizon','estimand','constraint'].every(k=>d[k])&&(!needsValue||d.constraintValue!=='')
  useEffect(()=>onEvidence({summary:complete?`${d.population} · ${d.treatment} vs ${d.comparator} · ${d.outcome} a ${d.horizon}`:'Contrato causal incompleto.',assumption:'Población, tratamiento, comparador, outcome, horizonte y restricción deben describir la misma decisión.',decision:complete?`Estimando ${d.estimand}; restricción ${d.constraint}${d.constraintValue!==''?` = ${d.constraintValue}`:''}.`:'No cerrar la decisión todavía.'}),[JSON.stringify(d)])
  const field=(key,label)=><label className="form-row"><b>{label}</b><select className="select" value={d[key]} onChange={e=>setD({...d,[key]:e.target.value,...(key==='constraint'?{constraintValue:''}:{})})}><option value="">Selecciona…</option>{DECISION_OPTIONS[key].map(x=><option key={x}>{x}</option>)}</select></label>
  return <div className="tool-body"><div className="decision-canvas-v7">{field('population','Población')}{field('treatment','Intervención')}{field('comparator','Comparador')}{field('outcome','Outcome')}{field('horizon','Horizonte')}{field('estimand','Estimando')}{field('constraint','Restricción')}{needsValue&&<label className="form-row"><b>Valor de la restricción</b>{d.constraint==='Riesgo de daño'?<select className="select" value={d.constraintValue} onChange={e=>setD({...d,constraintValue:e.target.value})}><option value="">Selecciona…</option><option>Baja</option><option>Media</option><option>Alta</option></select>:<input className="input" type="number" min="0" value={d.constraintValue} onChange={e=>setD({...d,constraintValue:e.target.value})} placeholder={d.constraint==='Capacidad máxima'?'4000':'40000'}/>}</label>}</div><div className={`notice ${complete?'notice-green':'notice-gold'}`}>{complete?'Contrato causal listo para contrastar con las demás especialidades.':'Completa todos los campos: esto es lo que el rol debe fijar antes de pedir “un modelo”.'}</div></div>
}

function ModelsSandbox({round,onEvidence}){
  const[estimator,setEstimator]=useState('drlearner');const[selected,setSelected]=useState(UPLIFT_CLIENTS[0]?.id||'')
  useEffect(()=>{if(round===1)onEvidence({summary:'Score alto y cambio incremental alto no son la misma cosa.',assumption:'P(Y|X) responde predicción; Y(1)-Y(0) responde intervención.',decision:'No priorizar automáticamente por score.'});else if(round===2)onEvidence({summary:'Comparación cruda −12 pp; ajustada +3.9 pp; IPW +4.2 pp.',assumption:'El ajuste sólo es causal si las variables bloquean la confusión relevante.',decision:'No cancelar basándose sólo en la tasa cruda.'});else if(round===3)onEvidence({summary:'El modelo puede segmentar, pero la regla de asignación define la comparabilidad.',assumption:'AUC y evidencia experimental responden preguntas diferentes.',decision:'Usar el score como apoyo, no como sustituto de un control válido.'})},[round])
  if(round===1){const rows=TOOL_PRACTICE.model[1];return <div className="tool-body"><div className="mini-model-table"><b>Cliente</b><b>P(Y=1)</b><b>Y(0)</b><b>Y(1)</b>{rows.map(r=><React.Fragment key={r.name}><span>{r.name}</span><span>{r.propensity}%</span><span>{r.p0}%</span><span>{r.p1}%</span></React.Fragment>)}</div><div className="notice">Compara quién probablemente convierte con quién cambia más por intervenir.</div></div>}
  if(round===2)return <div className="tool-body"><div className="model-method-grid"><div><b>Crudo</b><strong>−12.0 pp</strong></div><div><b>Regresión ajustada</b><strong>+3.9 pp</strong></div><div><b>IPW</b><strong>+4.2 pp</strong></div></div><div className="notice">Que dos métodos ajustados coincidan no demuestra identificación.</div></div>
  if(round===3)return <div className="tool-body"><div className="compare-panels"><div><b>Modelo predictivo</b><span>Ordena P(Y|X).</span></div><div><b>Experimento</b><span>Construye la comparación para ΔY por T.</span></div></div></div>
  const current=UPLIFT_CLIENTS.find(r=>r.id===selected)||UPLIFT_CLIENTS[0];const top=[...UPLIFT_CLIENTS].sort((a,b)=>Number(b[estimator])-Number(a[estimator])).slice(0,5)
  useEffect(()=>onEvidence({summary:`${ESTIMATORS[estimator].label}: ${top[0]?.name} lidera con ${(Number(top[0]?.[estimator]||0)*100).toFixed(1)} pp.`,assumption:'La concordancia entre estimadores no sustituye la identificación.',decision:'Priorizar efectos incrementales creíbles, no sólo score alto.'}),[estimator,selected])
  return <div className="tool-body"><div className="fac-toolbar">{Object.entries(ESTIMATORS).map(([k,m])=><button key={k} className={`btn ${estimator===k?'btn-primary':''}`} onClick={()=>setEstimator(k)}>{m.label}</button>)}</div><div className="card" style={{marginTop:12}}><label className="form-row"><b>Perfil que quieres inspeccionar</b><select className="select" value={selected} onChange={e=>setSelected(e.target.value)}>{UPLIFT_CLIENTS.map(r=><option key={r.id} value={r.id}>{r.name} · score {Math.round(Number(r.score)*100)}%</option>)}</select></label><div className="model-readout"><div><small>Perfil</small><b>{current?.name}</b><span>{current?.segment}</span></div><div><small>Score</small><b>{Math.round(Number(current?.score||0)*100)}%</b></div><div><small>{ESTIMATORS[estimator].label}</small><b>{(Number(current?.[estimator]||0)*100).toFixed(1)} pp</b></div></div></div><div className="top-cate"><b>Top 5 por efecto estimado</b>{top.map((r,i)=><span key={r.id}>{i+1}. {r.name} · score {Math.round(Number(r.score)*100)}% · {(Number(r[estimator])*100).toFixed(1)} pp</span>)}</div></div>
}

function DagSandbox({round,onEvidence}){
  const scenario=DAG_SCENARIOS[round]||DAG_SCENARIOS[2];const[edges,setEdges]=useState([]);const[adjust,setAdjust]=useState([]);const[src,setSrc]=useState('');const[dst,setDst]=useState('');const[diagnosed,setDiagnosed]=useState(false)
  useEffect(()=>{setEdges([]);setAdjust([]);setDiagnosed(false);setSrc('');setDst('')},[round])
  function add(){if(src&&dst&&src!==dst&&!edges.some(([a,b])=>a===src&&b===dst)){setEdges([...edges,[src,dst]]);setDiagnosed(false)}}
  const expected=scenario.expected.every(([a,b])=>edges.some(([x,y])=>x===a&&y===b));let result='Construye el grafo y diagnostica.';let cls='notice-gold'
  if(diagnosed){if(!expected){result='Falta al menos una relación necesaria para representar la hipótesis.'}else if(scenario.danger==='backdoor'&&!adjust.includes('Mora previa')){result='🔴 Backdoor abierto: Llamada ← Mora previa → Pago.';cls='notice-red'}else if(scenario.danger==='backdoor'){result='🟢 Ajustar Mora previa bloquea el camino de confusión.';cls='notice-green'}else if(scenario.danger==='mediator'&&adjust.includes('Satisfacción')){result='🔴 Satisfacción es posterior al tratamiento: ajustarla bloquea parte del efecto total.';cls='notice-red'}else if(scenario.danger==='mediator'){result='🟢 Para efecto total, evita controlar el mediador.';cls='notice-green'}else if(adjust.includes('Uso app')){result='🔴 Uso app actúa como collider; condicionarlo puede abrir sesgo.';cls='notice-red'}else{result='🟢 Evitar el collider mantiene cerrada la ruta espuria.';cls='notice-green'}}
  useEffect(()=>onEvidence({summary:diagnosed?result:'DAG aún sin diagnóstico.',assumption:'La estructura causal y temporalidad determinan qué ajustar.',decision:diagnosed?result:'Diagnostica antes de interpretar el estimador como causal.'}),[diagnosed,result,JSON.stringify(edges),JSON.stringify(adjust)])
  if(round===1)return <div className="tool-body"><div className="risk-checklist"><div><b>1</b><span>¿Qué le habría pasado al mismo cliente sin llamada?</span></div><div><b>2</b><span>¿Tenemos un comparador que represente ese futuro?</span></div><div><b>3</b><span>¿Qué variable previa puede hacer distintos a los grupos?</span></div></div></div>
  return <div className="tool-body"><div className="notice"><b>{scenario.title}</b><br/>{scenario.prompt}</div><div className="grid grid-2"><label className="form-row"><b>Origen</b><select className="select" value={src} onChange={e=>setSrc(e.target.value)}><option value="">Selecciona…</option>{scenario.nodes.map(n=><option key={n}>{n}</option>)}</select></label><label className="form-row"><b>Destino</b><select className="select" value={dst} onChange={e=>setDst(e.target.value)}><option value="">Selecciona…</option>{scenario.nodes.map(n=><option key={n}>{n}</option>)}</select></label></div><button className="btn" onClick={add} disabled={!src||!dst||src===dst}><Plus size={15}/> Añadir relación</button><div className="card" style={{marginTop:12}}><b>Relaciones propuestas</b>{edges.length?edges.map(([a,b],i)=><div key={`${a}-${b}-${i}`}>{a} → {b}</div>):<p>Aún no agregas relaciones.</p>}</div><div className="card" style={{marginTop:12}}><b>Variables por las que ajustarías</b>{scenario.nodes.map(n=><label className="choice" key={n}><input type="checkbox" checked={adjust.includes(n)} onChange={e=>setAdjust(v=>e.target.checked?[...v,n]:v.filter(x=>x!==n))}/>{n}</label>)}</div><button className="btn btn-primary" onClick={()=>setDiagnosed(true)}>Diagnosticar estructura</button><div className={`notice ${cls}`} style={{marginTop:12}}>{result}</div></div>
}

function ExperimentSandbox({round,onEvidence}){
  const[n,setN]=useState(2000);const[assignment,setAssignment]=useState('random');const[outcome,setOutcome]=useState('');const[horizon,setHorizon]=useState('')
  if(round<3){useEffect(()=>onEvidence({summary:'La pregunta todavía es qué grupo sería un comparador defendible.',assumption:'No hay ATE experimental sin una regla de asignación.',decision:'Preparar el diseño; la aleatorización se activa en ronda 3.'}),[round]);return <div className="tool-body"><div className="locked-tool"><b>🐢 Experiment Designer se activa en ronda 3</b><p>Antes de eso, tu trabajo es exigir un comparador defendible y no llamar “causal” a cualquier diferencia.</p></div></div>}
  const drift={200:.6,2000:0,20000:.1}[n]||0;const bias=assignment==='random'?0:assignment==='model'?7.8:-4.9;const c=EXPERIMENT_BASE.controlRate,t=EXPERIMENT_BASE.treatmentRate+drift+bias,diff=t-c;const se=Math.sqrt((t/100*(1-t/100))/(n/2)+(c/100*(1-c/100))/(n/2))*100;const lo=diff-1.96*se,hi=diff+1.96*se;const causal=assignment==='random'
  useEffect(()=>onEvidence({summary:`${assignment==='random'?'Azar':assignment==='model'?'Modelo':'Asesor'} · N=${n.toLocaleString()} · ${causal?'ATE estimado':'Diferencia observada'} ${diff.toFixed(1)} pp · IC95% [${lo.toFixed(1)}, ${hi.toFixed(1)}].`,assumption:causal?'La asignación aleatoria sostiene comparabilidad en expectativa.':'Más N no elimina el sesgo de selección de una regla no aleatoria.',decision:outcome&&horizon?`Medir ${outcome} a ${horizon}.`:'Falta fijar outcome y horizonte.'}),[n,assignment,outcome,horizon,diff])
  return <div className="tool-body"><div className="experiment-controls"><label><b>Asignación</b><select className="select" value={assignment} onChange={e=>setAssignment(e.target.value)}><option value="advisor">Asesor</option><option value="model">Modelo</option><option value="random">Azar</option></select></label><label><b>N</b><select className="select" value={n} onChange={e=>setN(Number(e.target.value))}><option>200</option><option>2000</option><option>20000</option></select></label><label><b>Outcome</b><select className="select" value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="">Selecciona…</option>{DECISION_OPTIONS.outcome.map(x=><option key={x}>{x}</option>)}</select></label><label><b>Horizonte</b><select className="select" value={horizon} onChange={e=>setHorizon(e.target.value)}><option value="">Selecciona…</option>{DECISION_OPTIONS.horizon.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="experiment-result"><div><small>Tratamiento</small><b>{t.toFixed(1)}%</b></div><div><small>Control</small><b>{c.toFixed(1)}%</b></div><div><small>{causal?'ATE estimado':'Diferencia observada'}</small><b>{diff>=0?'+':''}{diff.toFixed(1)} pp</b></div><div><small>IC95%</small><b>[{lo.toFixed(1)}, {hi.toFixed(1)}]</b></div></div><div className={`notice ${causal?'notice-green':'notice-gold'}`}>{causal?'Cambia N y observa cómo cambia la precisión.':'Prueba N=20.000: el intervalo se estrecha, pero el sesgo de selección sigue existiendo.'}</div></div>
}

function CopilotSandbox({onEvidence}){const[checks,setChecks]=useState({cost:false,capacity:false,harm:false,reversible:false});useEffect(()=>{const n=Object.values(checks).filter(Boolean).length;onEvidence({summary:`Auditoría de política: ${n}/4 riesgos revisados.`,assumption:'Una política rentable en promedio puede fallar por capacidad, daño o irreversibilidad.',decision:n===4?'Decisión auditada: puede discutirse con el Líder de Estrategia.':'Faltan riesgos operativos por revisar.'})},[JSON.stringify(checks)]);return <div className="tool-body"><div className="risk-checklist">{[['cost','¿El costo puede destruir el valor incremental?'],['capacity','¿La capacidad real alcanza?'],['harm','¿Algún segmento puede salir perjudicado?'],['reversible','¿La acción es reversible si la evidencia falla?']].map(([k,t],i)=><label key={k} className="choice"><input type="checkbox" checked={checks[k]} onChange={e=>setChecks({...checks,[k]:e.target.checked})}/><b>{i+1}</b><span>{t}</span></label>)}</div><div className="notice">Este rol es apoyo opcional: no crea una quinta evidencia necesaria para 4/4.</div></div>}

export default function FacilitatorRoleInspector(){
  const[role,setRole]=useState('business');const[round,setRound]=useState(1);const[evidence,setEvidence]=useState(null);const[policyEvidence,setPolicyEvidence]=useState(null)
  useEffect(()=>{setEvidence(null);setPolicyEvidence(null)},[role,round])
  if(!getFacilitatorToken())return <Layout subtitle="Inspector docente"><div className="card card-accent"><h2>Primero entra como facilitador</h2><p>Este sandbox usa una credencial de facilitador en tu navegador para mantenerlo separado del flujo del estudiante.</p><a className="btn btn-primary" href="facilitator.html">Ir al facilitador</a></div></Layout>
  const meta=ROLE_TOOLS[role];const fakeState={preview:true,player:{id:'preview',role_code:role},game:{round,phase:'round'},segments:SAMPLE_SEGMENTS,policy:{capacity:12000}}
  let Body=role==='business'?DecisionSandbox:role==='data'?ModelsSandbox:role==='context'?DagSandbox:role==='integrator'?ExperimentSandbox:CopilotSandbox
  return <Layout subtitle="Inspector docente" actions={<a className="btn btn-ghost" href="facilitator.html"><ArrowLeft size={15}/> Volver al facilitador</a>}><div className="section-title"><div><div className="eyebrow">SANDBOX DOCENTE · NO ESCRIBE EN LA PARTIDA</div><h1>Experimenta con cada rol</h1><p>Cambia de rol y de ronda. Nada de lo que hagas aquí ocupa cupos, compra ayudas, comparte evidencia ni altera puntajes.</p></div></div><div className="card"><div className="eyebrow">ROL</div><div className="fac-toolbar">{ROLES.map(([code,emoji,label])=><button key={code} className={`btn ${role===code?'btn-primary':''}`} onClick={()=>setRole(code)}>{emoji} {label}</button>)}</div><div className="eyebrow" style={{marginTop:14}}>RONDA</div><div className="fac-toolbar">{[1,2,3,4].map(r=><button key={r} className={`btn ${round===r?'btn-primary':''}`} onClick={()=>setRound(r)}>R{r}</button>)}<button className="btn" onClick={()=>{setEvidence(null);setPolicyEvidence(null);setRole(x=>x)}}><RotateCcw size={15}/> Reiniciar vista</button></div></div><div style={{marginTop:16}}><RoleReveal state={fakeState} phase="round"/></div><div className="tool-card" style={{marginTop:16,borderColor:meta.color}}><div className="tool-head"><div><div className="eyebrow"><FlaskConical size={15}/> INSPECCIÓN INTERACTIVA · RONDA {round}</div><h3>{meta.tool}</h3><p>{meta.purpose}</p></div></div><div className="notice"><b>Misión de esta ronda:</b> {ROLE_TASKS[round]?.[role]}</div><div className="causal-four"><div><b>1 · Pregunta</b><span>{TOOL_GUIDE[role].question}</span></div><div><b>2 · Evidencia</b><span>{evidence?.summary||'Interactúa con la herramienta.'}</span></div><div><b>3 · Supuesto</b><span>{evidence?.assumption||TOOL_GUIDE[role].assumption}</span></div><div><b>4 · Decisión</b><span>{evidence?.decision||TOOL_GUIDE[role].decision}</span></div></div><Body key={`${role}-${round}`} round={round} state={fakeState} onEvidence={setEvidence}/><Evidence value={evidence}/>{role==='business'&&round>=4&&<div className="tool-card" style={{marginTop:16}}><div className="tool-head"><div><div className="eyebrow">SEGUNDA MITAD DEL ROL</div><h3>Policy Simulator</h3><p>Después de definir la pregunta, cierra con una política factible.</p></div></div><StrategyPolicyTool state={fakeState} onEvidence={setPolicyEvidence}/><Evidence value={policyEvidence}/></div>}</div></Layout>
}
