import React,{useEffect,useState}from'react'
import{Bot,Clock3,Eye,GraduationCap,LockKeyhole,Pause,Play,RotateCcw,SkipForward,Users,Presentation,MonitorCheck,Shuffle,RefreshCw,UserMinus}from'lucide-react'
import{Layout}from'../components/Layout'
import{Leaderboard}from'../components/Leaderboard'
import{LessonPanel}from'../components/LessonPanel'
import{ReadinessPanel}from'../components/ReadinessPanel'
import{RoleInspector}from'../components/RoleInspector'
import{bootstrapGame,invoke,saveFacilitatorToken,saveFacilitatorGameCode,getFacilitatorGameCode,getFacilitatorToken}from'../lib/api'
import{LESSONS}from'../learning'
import{attendancePlan,attendanceSummary,MAX_HUMANS}from'../attendance'

const jitter=base=>Math.round(base*(.82+Math.random()*.36))
const makeCode=()=>`CQ-${crypto.randomUUID().replaceAll('-','').slice(0,6).toUpperCase()}`

function Login({onLogin}){const[code,setCode]=useState('');const[pin,setPin]=useState('');const[err,setErr]=useState('');const[busy,setBusy]=useState(false);const[showCreate,setShowCreate]=useState(false);const[master,setMaster]=useState('');async function go(){setBusy(true);setErr('');try{const r=await invoke('facilitator-login',{game_code:code.trim().toUpperCase(),pin},'facilitator');saveFacilitatorToken(r.token);saveFacilitatorGameCode(code);onLogin()}catch(e){setErr(e.message)}finally{setBusy(false)}}async function create(){setBusy(true);setErr('');try{const r=await bootstrapGame({game_code:code.trim().toUpperCase(),pin,bootstrap_secret:master});saveFacilitatorGameCode(r.game_code||code);setShowCreate(false);setMaster('');setErr('Partida creada. Ya puedes entrar con el PIN definido.')}catch(e){setErr(e.message)}finally{setBusy(false)}}function toggleCreate(){setShowCreate(v=>{const next=!v;if(next&&!code)setCode(makeCode());return next})}return <Layout subtitle="Facilitador"><div className="grid grid-2"><div className="card card-accent"><div className="eyebrow">CONTROL DOCENTE</div><h2>Entrar a una sesión</h2><div className="form-row"><label>Código</label><input className="input" placeholder="Código de esta sesión" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></div><div className="form-row"><label>PIN</label><input className="input" type="password" value={pin} onChange={e=>setPin(e.target.value)}/></div>{err&&<div className={`notice ${err.startsWith('Partida creada')?'notice-green':'notice-red'}`}>{err}</div>}<button className="btn btn-primary" disabled={busy||code.trim().length<4||pin.length<8} onClick={go}>Entrar</button></div><div className="card"><h3>Nueva partida</h3><p>Genera un código distinto para cada sesión; no publiques un código fijo permanente.</p><button className="btn" onClick={toggleCreate}>{showCreate?'Cancelar':'Crear partida'}</button>{showCreate&&<><div className="form-row"><label>Código de participantes</label><div className="fac-toolbar"><input className="input" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><button className="btn" type="button" onClick={()=>setCode(makeCode())}><Shuffle size={15}/> Generar otro</button></div></div><div className="form-row"><label>PIN del facilitador</label><input className="input" type="password" value={pin} onChange={e=>setPin(e.target.value)}/></div><div className="form-row"><label>Clave maestra</label><input className="input" type="password" value={master} onChange={e=>setMaster(e.target.value)}/></div><button className="btn btn-primary" disabled={busy||code.length<4||pin.length<8||!master} onClick={create}>Crear esta sesión</button></>}</div></div></Layout>}

function useRemote(){const[state,setState]=useState(null);const[err,setErr]=useState('');async function refresh(){try{const x=await invoke('leaderboard',{},'facilitator');setState(x);setErr('');return x}catch(e){setErr(e.message);return null}}useEffect(()=>{let stop=false,t;const loop=async()=>{await refresh();if(!stop)t=setTimeout(loop,jitter(3200))};loop();return()=>{stop=true;clearTimeout(t)}},[]);return{state,err,refresh}}

function Console(){const{state,err,refresh}=useRemote();const[busy,setBusy]=useState(false);const[info,setInfo]=useState('');if(!state)return <Layout subtitle="Facilitador"><div className="card">Conectando… {err}</div></Layout>;const g=state.game,lesson=LESSONS[g.round];const pc=Number(g.player_count||0),hc=Number(g.human_count||0),bc=Number(g.bot_count||0),tr=state.transfer||{};const legacyTopology=Boolean(g.legacy_topology),rosterLocked=Boolean(g.roster_locked);const plan=attendancePlan(hc),teamTarget=Number(g.team_target||plan.teams),coreTarget=Number(g.core_target||4),maxHumans=Number(g.max_humans||MAX_HUMANS);async function act(action,seconds=60){if(action==='reset'&&!confirm('¿Resetear sesión completa?'))return;if(action==='prune_offline'&&!confirm('Se eliminarán de la lista quienes lleven al menos 3 minutos sin conexión. ¿Continuar?'))return;setBusy(true);setInfo('');try{const r=await invoke('facilitator-transition',{action,seconds},'facilitator');if(action==='seed_bots')setInfo(`Ensayo cerrado: ${r.players} participantes · ${r.bots} bots · ${r.team_target||teamTarget} equipos.`);if(action==='rebalance')setInfo(`Equipos recalculados: ${(r.sizes||[]).join('–')} (${r.team_target||teamTarget} equipos).`);if(action==='prune_offline')setInfo(`Ausentes retirados: ${r.removed||0}. La lista volvió a equilibrarse.`);await refresh()}catch(e){alert(e.message)}finally{setBusy(false)}}const canLesson=['lobby','briefing'].includes(g.phase)&&hc>0;const canOpen=g.phase==='lesson';const canClose=['round','paused'].includes(g.phase);const canReveal=g.phase==='closed';const canTeach=g.phase==='reveal';const canCheck=g.phase==='teaching';const canNext=['microcheck','teaching','reveal'].includes(g.phase);const canTime=['round','paused'].includes(g.phase);const canAdjustRoster=['lobby','briefing'].includes(g.phase)&&!rosterLocked&&!legacyTopology;const canSeed=canAdjustRoster&&pc<maxHumans;return <Layout subtitle="Facilitador" actions={<><span className="pill">Código <strong>{g.code}</strong></span><span className="pill">Ronda <strong>{g.round}/4</strong></span><a className="btn btn-ghost" href="system-check.html" target="_blank" rel="noreferrer"><MonitorCheck size={15}/> Prueba previa</a><a className="btn btn-ghost" href={`wall.html?game=${encodeURIComponent(getFacilitatorGameCode())}`} target="_blank" rel="noreferrer">Abrir wall</a></>}>
<div className="grid grid-4"><div className="card"><div className="metric"><span>Estado</span><strong style={{fontSize:22}}>{g.phase.toUpperCase()}</strong><small>{g.public_message}</small></div></div><div className="card"><div className="metric"><span>Participantes</span><strong>{pc}/{maxHumans}</strong><small>{hc} humanos · {bc} bots</small></div></div><div className="card"><div className="metric"><span>Equipos activos</span><strong>{teamTarget}</strong><small>{rosterLocked?'lista cerrada':'provisional hasta iniciar'}</small></div></div><div className="card"><div className="metric"><span>Bloque docente</span><strong>{lesson.minutes} min</strong><small>{lesson.title}</small></div></div></div>
<div className="grid grid-3" style={{marginTop:14}}><div className="card"><div className="metric"><span>Pre causal</span><strong>{tr.pre_completed||0}/{hc||0}</strong><small>promedio {tr.pre_avg??'—'} / 4</small></div></div><div className="card"><div className="metric"><span>Post transferencia</span><strong>{tr.post_completed||0}/{hc||0}</strong><small>promedio {tr.post_avg??'—'} / 4</small></div></div><div className="card"><div className="metric"><span>Cambio observado</span><strong>{tr.delta===null||tr.delta===undefined?'—':`${Number(tr.delta)>=0?'+':''}${tr.delta}`}</strong><small>puntos sobre 4 · diagnóstico, no leaderboard</small></div></div></div>
{legacyTopology&&<div className="notice notice-gold" style={{marginTop:14}}><b>Sesión heredada detectada.</b> Esta partida conserva temporalmente 4 equipos × 5 roles para no alterar una sesión ya iniciada. Al resetear, pasa a la arquitectura adaptativa de 4 roles.</div>}
<div className="section-title"><h2>Simulador docente de equipo completo</h2><p>Recorre tú solo todo lo que leerían los participantes: misión, diagnóstico, cuatro perspectivas privadas, herramientas reales, Mesa de Evidencia, decisión, reveal y microcheck. Esta vista no escribe en Supabase.</p></div><details className="card"><summary style={{cursor:'pointer',fontWeight:800,fontSize:17}}>🧪 Simular un equipo completo</summary><div style={{marginTop:16}}><RoleInspector/></div></details>
{['lobby','briefing'].includes(g.phase)&&!legacyTopology&&<><div className="section-title"><h2>Antes de la sesión</h2><p>La app mantiene <b>cuatro roles</b> y adapta el número de equipos para que, siempre que la asistencia lo permita, cada grupo tenga 3–4 personas. Equipo y rol son provisionales hasta iniciar la primera mini-clase.</p></div><div className={`notice ${plan.preferred?'notice-green':'notice-gold'}`}><b>Plan actual · {hc} humano(s): {attendanceSummary(hc)}</b><br/>{hc===15?'15 → 4 equipos: 4–4–4–3.':hc===16?'16 → 4 equipos completos: 4–4–4–4.':hc===17?'17 → 5 equipos: 4–4–3–3–3.':hc===18?'18 → 5 equipos: 4–4–4–3–3.':hc===19?'19 → 5 equipos: 4–4–4–4–3.':hc===28?'28 → 7 equipos completos: 4–4–4–4–4–4–4.':plan.preferred?'Los grupos quedan entre 3 y 4 integrantes sin crear un quinto rol.':'La plataforma puede operar, pero hay al menos un grupo con menos de 3 personas; conviene ajustar la dinámica antes de empezar.'}</div>{canAdjustRoster&&<div className="card" style={{marginTop:12}}><div className="fac-toolbar"><button className="btn" disabled={busy} onClick={()=>act('rebalance')}><RefreshCw size={15}/> Recalcular equipos ahora</button><button className="btn" disabled={busy} onClick={()=>act('prune_offline',180)}><UserMinus size={15}/> Retirar ausentes &gt;3 min</button></div><p className="muted-copy" style={{marginBottom:0}}>Al pulsar <b>Presentar concepto y poderes</b> en R1, el servidor hace un último rebalanceo y congela la lista. Después sólo se permiten reingresos conocidos.</p></div>}<ReadinessPanel/></>}
<div className="section-title"><h2>1 · Enseñar</h2><p>La ronda no se puede abrir antes de presentar el concepto. Los poderes avanzados aparecen sólo cuando ya fueron explicados.</p></div><LessonPanel round={g.round} facilitator/>
<div className="card teaching-flow" style={{marginTop:16}}><div><b>Secuencia recomendada</b><p>Explica {lesson.minutes} min → demuestra 2–3 min → pulsa <b>Presentar concepto</b> → envía a las {teamTarget} salas → abre laboratorio. Cada rol recibe información distinta y debe llevar una evidencia propia a la Mesa. En equipos de tres, Modelos cubre Experimentos con un módulo separado.</p></div><div className="fac-toolbar"><button className="btn btn-primary" disabled={busy||!canLesson} onClick={()=>act('lesson')}><Presentation size={16}/> Presentar concepto y poderes</button><button className="btn btn-primary" disabled={busy||!canOpen} onClick={()=>act('open')}><Play size={16}/> Abrir laboratorio</button></div></div>
{['lobby','briefing'].includes(g.phase)&&<><div className="section-title"><h2>Ensayo técnico</h2><p>Los bots sirven para probar infraestructura; no sustituyen aprendizaje humano. Al completar con bots, la lista de ensayo queda cerrada para que la topología no cambie durante la prueba.</p></div><div className="card"><div className="fac-toolbar"><button className="btn" disabled={busy||!canSeed} onClick={()=>act('seed_bots')}><Bot size={16}/> Completar ensayo con bots</button><a className="btn" href="play.html" target="_blank" rel="noreferrer"><Users size={16}/> Abrir participante</a></div></div></>}
{hc===0&&<div className="notice notice-red" style={{marginTop:12}}>Debe existir al menos un humano antes de presentar la mini-clase.</div>}{info&&<div className="notice notice-green" style={{marginTop:12}}>{info}</div>}
<div className="section-title"><h2>2 · Dirigir el juego</h2><p>Reveal y cierre pedagógico ocurren en sala principal. La Llamada al Capítulo está retirada por ahora: el aprendizaje debe salir de la interdependencia del equipo y las herramientas de cada rol.</p></div><div className="card"><div className="fac-toolbar"><button className="btn" disabled={busy||!canClose} onClick={()=>act('close')}><LockKeyhole size={16}/> Cerrar decisiones</button><button className="btn" disabled={busy||!canReveal} onClick={()=>act('reveal')}><Eye size={16}/> Revelar</button><button className="btn" disabled={busy||!canTeach} onClick={()=>act('teach')}><GraduationCap size={16}/> Cierre pedagógico</button><button className="btn" disabled={busy||!canCheck} onClick={()=>act('microcheck')}>Microcheck</button><button className="btn" disabled={busy||!canNext} onClick={()=>act('next')}><SkipForward size={16}/> Siguiente ronda</button><button className="btn" disabled={busy||!canTime} onClick={()=>act('add_time',60)}><Clock3 size={16}/> +60 s</button>{g.phase==='paused'?<button className="btn btn-primary" onClick={()=>act('resume')}><Play size={16}/> Reanudar</button>:<button className="btn" disabled={busy||g.phase!=='round'} onClick={()=>act('pause')}><Pause size={16}/> Pausar</button>}<button className="btn" disabled={busy||g.phase==='round'} onClick={()=>act('reset')}><RotateCcw size={16}/> Reset</button></div></div>
{err&&<div className="notice notice-red" style={{marginTop:12}}>Conexión: {err}</div>}
<div className="section-title"><h2>3 · Observar</h2><p><b>Cobertura 0–{coreTarget}</b> indica cuántas responsabilidades núcleo produjeron evidencia. La decisión final nueva requiere 4/4 (o el doble sombrero explícito en equipos de tres); cobertura completa no garantiza causalidad correcta.</p></div><div className="card"><div className="team-status header"><div>Equipo</div><div>H/B</div><div>Online</div><div>Locked</div><div>Impacto</div><div>Evid.</div><div>Checks</div></div>{state.teams.map(t=>{const coverage=Number(t.core_coverage??Math.min(Number(t.contributions||0),coreTarget));return <div className="team-status" key={t.id}><div><b>{t.name}</b><small style={{display:'block',color:coverage<coreTarget?'var(--red)':'var(--green)'}}>Cobertura {coverage}/{coreTarget}</small></div><div>{t.humans||0}/{t.bots||0}</div><div>{t.online||0}</div><div>{t.locked?'✓':'…'}</div><div>{t.score.impact}</div><div>{t.score.evidence}</div><div>{t.check_correct||0}</div></div>})}</div><div className="grid grid-2" style={{marginTop:16}}><div className="card"><h3>Leaderboard</h3><Leaderboard state={state}/></div><div className="card"><h3>Auditoría</h3><div className="audit">{(state.audit||[]).map((e,i)=><div className="audit-row" key={i}><b>{new Date(e.at).toLocaleTimeString()}</b> · {e.type}</div>)}</div></div></div>
</Layout>}

export default function SecureFacilitatorLearning(){const[token,setToken]=useState(()=>getFacilitatorToken());return token?<Console/>:<Login onLogin={()=>setToken(getFacilitatorToken())}/>}
