import React,{useEffect,useState}from'react'
import{Bot,Clock3,Eye,GraduationCap,LockKeyhole,Pause,Play,RotateCcw,SkipForward,Users,Presentation,MonitorCheck,Shuffle}from'lucide-react'
import{Layout}from'../components/Layout'
import{Leaderboard}from'../components/Leaderboard'
import{LessonPanel}from'../components/LessonPanel'
import{ReadinessPanel}from'../components/ReadinessPanel'
import{ExpertAvailabilityPanel}from'../components/ExpertAvailabilityPanel'
import{ExpertQueue}from'../components/ExpertQueue'
import{RoleInspector}from'../components/RoleInspector'
import{bootstrapGame,invoke,saveFacilitatorToken,saveFacilitatorGameCode,getFacilitatorGameCode,getFacilitatorToken}from'../lib/api'
import{ROUND_COPY}from'../content'
import{LESSONS}from'../learning'

const jitter=base=>Math.round(base*(.82+Math.random()*.36))
const makeCode=()=>`CQ-${crypto.randomUUID().replaceAll('-','').slice(0,6).toUpperCase()}`

function Login({onLogin}){const[code,setCode]=useState('');const[pin,setPin]=useState('');const[err,setErr]=useState('');const[busy,setBusy]=useState(false);const[showCreate,setShowCreate]=useState(false);const[master,setMaster]=useState('');async function go(){setBusy(true);setErr('');try{const r=await invoke('facilitator-login',{game_code:code.trim().toUpperCase(),pin},'facilitator');saveFacilitatorToken(r.token);saveFacilitatorGameCode(code);onLogin()}catch(e){setErr(e.message)}finally{setBusy(false)}}async function create(){setBusy(true);setErr('');try{const r=await bootstrapGame({game_code:code.trim().toUpperCase(),pin,bootstrap_secret:master});saveFacilitatorGameCode(r.game_code||code);setShowCreate(false);setMaster('');setErr('Partida creada. Ya puedes entrar con el PIN definido.')}catch(e){setErr(e.message)}finally{setBusy(false)}}function toggleCreate(){setShowCreate(v=>{const next=!v;if(next&&!code)setCode(makeCode());return next})}return <Layout subtitle="Facilitador"><div className="grid grid-2"><div className="card card-accent"><div className="eyebrow">CONTROL DOCENTE</div><h2>Entrar a una sesión</h2><div className="form-row"><label>Código</label><input className="input" placeholder="Código de esta sesión" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></div><div className="form-row"><label>PIN</label><input className="input" type="password" value={pin} onChange={e=>setPin(e.target.value)}/></div>{err&&<div className={`notice ${err.startsWith('Partida creada')?'notice-green':'notice-red'}`}>{err}</div>}<button className="btn btn-primary" disabled={busy||code.trim().length<4||pin.length<8} onClick={go}>Entrar</button></div><div className="card"><h3>Nueva partida</h3><p>Genera un código distinto para cada sesión; no publiques un código fijo permanente.</p><button className="btn" onClick={toggleCreate}>{showCreate?'Cancelar':'Crear partida'}</button>{showCreate&&<><div className="form-row"><label>Código de participantes</label><div className="fac-toolbar"><input className="input" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><button className="btn" type="button" onClick={()=>setCode(makeCode())}><Shuffle size={15}/> Generar otro</button></div></div><div className="form-row"><label>PIN del facilitador</label><input className="input" type="password" value={pin} onChange={e=>setPin(e.target.value)}/></div><div className="form-row"><label>Clave maestra</label><input className="input" type="password" value={master} onChange={e=>setMaster(e.target.value)}/></div><button className="btn btn-primary" disabled={busy||code.length<4||pin.length<8||master.length<12} onClick={create}>Crear esta sesión</button></>}</div></div></Layout>}

function useRemote(){const[state,setState]=useState(null);const[err,setErr]=useState('');async function refresh(){try{const x=await invoke('leaderboard',{},'facilitator');setState(x);setErr('');return x}catch(e){setErr(e.message);return null}}useEffect(()=>{let stop=false,t;const loop=async()=>{await refresh();if(!stop)t=setTimeout(loop,jitter(3200))};loop();return()=>{stop=true;clearTimeout(t)}},[]);return{state,err,refresh}}

function Console(){const{state,err,refresh}=useRemote();const[busy,setBusy]=useState(false);const[info,setInfo]=useState('');if(!state)return <Layout subtitle="Facilitador"><div className="card">Conectando… {err}</div></Layout>;const g=state.game,lesson=LESSONS[g.round];const pc=Number(g.player_count||0),hc=Number(g.human_count||0),bc=Number(g.bot_count||0),tr=state.transfer||{};async function act(action,seconds=60){if(action==='reset'&&!confirm('¿Resetear sesión completa?'))return;setBusy(true);setInfo('');try{const r=await invoke('facilitator-transition',{action,seconds},'facilitator');if(action==='seed_bots')setInfo(`Ensayo: ${r.players} participantes, ${r.bots} bots.`);await refresh()}catch(e){alert(e.message)}finally{setBusy(false)}}const canLesson=['lobby','briefing'].includes(g.phase)&&hc>0;const canOpen=g.phase==='lesson';const canClose=['round','paused'].includes(g.phase);const canReveal=g.phase==='closed';const canTeach=g.phase==='reveal';const canCheck=g.phase==='teaching';const canNext=['microcheck','teaching','reveal'].includes(g.phase);const canTime=['round','paused'].includes(g.phase);const canSeed=['lobby','briefing'].includes(g.phase)&&pc<20;return <Layout subtitle="Facilitador" actions={<><span className="pill">Código <strong>{g.code}</strong></span><span className="pill">Ronda <strong>{g.round}/4</strong></span><a className="btn btn-ghost" href="system-check.html" target="_blank" rel="noreferrer"><MonitorCheck size={15}/> Prueba previa</a><a className="btn btn-ghost" href={`wall.html?game=${encodeURIComponent(getFacilitatorGameCode())}`} target="_blank" rel="noreferrer">Abrir wall</a></>}>
<div className="grid grid-4"><div className="card"><div className="metric"><span>Estado</span><strong style={{fontSize:22}}>{g.phase.toUpperCase()}</strong><small>{g.public_message}</small></div></div><div className="card"><div className="metric"><span>Participantes</span><strong>{pc}/20</strong><small>{hc} humanos · {bc} bots</small></div></div><div className="card"><div className="metric"><span>Equipos listos</span><strong>{state.teams.filter(t=>t.locked).length}/4</strong><small>decisiones</small></div></div><div className="card"><div className="metric"><span>Bloque docente</span><strong>{lesson.minutes} min</strong><small>{lesson.title}</small></div></div></div>
<div className="grid grid-3" style={{marginTop:14}}><div className="card"><div className="metric"><span>Pre causal</span><strong>{tr.pre_completed||0}/{hc||0}</strong><small>promedio {tr.pre_avg??'—'} / 4</small></div></div><div className="card"><div className="metric"><span>Post transferencia</span><strong>{tr.post_completed||0}/{hc||0}</strong><small>promedio {tr.post_avg??'—'} / 4</small></div></div><div className="card"><div className="metric"><span>Cambio observado</span><strong>{tr.delta===null||tr.delta===undefined?'—':`${Number(tr.delta)>=0?'+':''}${tr.delta}`}</strong><small>puntos sobre 4 · diagnóstico, no leaderboard</small></div></div></div>
<div className="section-title"><h2>Inspección docente</h2><p>Prueba cualquiera de las cinco especialidades y cualquier ronda sin crear participantes ficticios ni alterar la sesión real.</p></div><details className="card"><summary style={{cursor:'pointer',fontWeight:800,fontSize:17}}>🧪 Probar roles y herramientas</summary><div style={{marginTop:16}}><RoleInspector/></div></details>
{['lobby','briefing'].includes(g.phase)&&<><div className="section-title"><h2>Antes de la sesión</h2><p>Comprueba que los participantes esperados hayan ejecutado la prueba. La configuración objetivo es 5 especialistas por equipo; una ausencia no bloquea la sesión, pero deja visible la evidencia faltante.</p></div><ReadinessPanel/></>}
<div className="section-title"><h2>1 · Enseñar</h2><p>La ronda no se puede abrir antes de presentar el concepto. Los poderes avanzados aparecen sólo cuando ya fueron explicados.</p></div><LessonPanel round={g.round} facilitator/>
<div className="card teaching-flow" style={{marginTop:16}}><div><b>Secuencia recomendada</b><p>Explica {lesson.minutes} min → demuestra 2–3 min → pulsa <b>Presentar concepto</b> → envía a las 4 salas → abre laboratorio. Si falta Experimentos, Modelos puede cubrir ese módulo mediante doble sombrero.</p></div><div className="fac-toolbar"><button className="btn btn-primary" disabled={busy||!canLesson} onClick={()=>act('lesson')}><Presentation size={16}/> Presentar concepto y poderes</button><button className="btn btn-primary" disabled={busy||!canOpen} onClick={()=>act('open')}><Play size={16}/> Abrir laboratorio</button></div></div>
{['lobby','briefing'].includes(g.phase)&&<><div className="section-title"><h2>Ensayo</h2><p>Para probar sin 20 personas.</p></div><div className="card"><div className="fac-toolbar"><button className="btn" disabled={busy||!canSeed} onClick={()=>act('seed_bots')}><Bot size={16}/> Completar con bots</button><a className="btn" href="play.html" target="_blank" rel="noreferrer"><Users size={16}/> Abrir participante</a></div></div></>}
{hc===0&&<div className="notice notice-red" style={{marginTop:12}}>Debe existir al menos un humano antes de presentar la mini-clase.</div>}{info&&<div className="notice notice-green" style={{marginTop:12}}>{info}</div>}
<div className="section-title"><h2>2 · Llamada al Capítulo</h2><p>El Game Master dirige y no se compra. Si un equipo compra una llamada, cualquiera de los tres facilitadores expertos disponibles puede atenderla. Los tres deben manejar una base común de causalidad, experimentación y decisión; la ayuda sólo puede usar conceptos ya enseñados.</p></div><ExpertAvailabilityPanel round={g.round}/><ExpertQueue audit={state.audit||[]}/>
<div className="section-title"><h2>3 · Dirigir el juego</h2><p>Reveal y cierre pedagógico ocurren en sala principal. No sacrifiques el debrief para recuperar tiempo.</p></div><div className="card"><div className="fac-toolbar"><button className="btn" disabled={busy||!canClose} onClick={()=>act('close')}><LockKeyhole size={16}/> Cerrar decisiones</button><button className="btn" disabled={busy||!canReveal} onClick={()=>act('reveal')}><Eye size={16}/> Revelar</button><button className="btn" disabled={busy||!canTeach} onClick={()=>act('teach')}><GraduationCap size={16}/> Cierre pedagógico</button><button className="btn" disabled={busy||!canCheck} onClick={()=>act('microcheck')}>Microcheck</button><button className="btn" disabled={busy||!canNext} onClick={()=>act('next')}><SkipForward size={16}/> Siguiente ronda</button><button className="btn" disabled={busy||!canTime} onClick={()=>act('add_time',60)}><Clock3 size={16}/> +60 s</button>{g.phase==='paused'?<button className="btn btn-primary" onClick={()=>act('resume')}><Play size={16}/> Reanudar</button>:<button className="btn" disabled={busy||g.phase!=='round'} onClick={()=>act('pause')}><Pause size={16}/> Pausar</button>}<button className="btn" disabled={busy||g.phase==='round'} onClick={()=>act('reset')}><RotateCcw size={16}/> Reset</button></div></div>
{err&&<div className="notice notice-red" style={{marginTop:12}}>Conexión: {err}</div>}
<div className="section-title"><h2>4 · Observar</h2><p><b>Cobertura 0–5</b> indica cuántas especialidades produjeron evidencia. 5/5 no significa automáticamente causalidad correcta: revisa también los chequeos de coherencia de la mesa.</p></div><div className="card"><div className="team-status header"><div>Equipo</div><div>H/B</div><div>Online</div><div>Locked</div><div>Impacto</div><div>Evid.</div><div>Checks</div></div>{state.teams.map(t=>{const coverage=Number(t.core_coverage??Math.min(Number(t.contributions||0),5));return <div className="team-status" key={t.id}><div><b>{t.name}</b><small style={{display:'block',color:coverage<5?'var(--red)':'var(--green)'}}>Cobertura {coverage}/5</small></div><div>{t.humans||0}/{t.bots||0}</div><div>{t.online||0}</div><div>{t.locked?'✓':'…'}</div><div>{t.score.impact}</div><div>{t.score.evidence}</div><div>{t.check_correct||0}</div></div>})}</div><div className="grid grid-2" style={{marginTop:16}}><div className="card"><h3>Leaderboard</h3><Leaderboard state={state}/></div><div className="card"><h3>Auditoría</h3><div className="audit">{(state.audit||[]).map((e,i)=><div className="audit-row" key={i}><b>{new Date(e.at).toLocaleTimeString()}</b> · {e.type}</div>)}</div></div></div>
</Layout>}

export default function SecureFacilitatorLearning(){const[token,setToken]=useState(()=>getFacilitatorToken());return token?<Console/>:<Login onLogin={()=>setToken(getFacilitatorToken())}/>}
