import React,{useEffect,useState}from'react'
import{Bot,Clock3,Eye,GraduationCap,LockKeyhole,Pause,Play,RotateCcw,SkipForward,Users,Presentation,MonitorCheck}from'lucide-react'
import{Layout}from'../components/Layout'
import{Leaderboard}from'../components/Leaderboard'
import{LessonPanel}from'../components/LessonPanel'
import{ReadinessPanel}from'../components/ReadinessPanel'
import{ExpertAvailabilityPanel}from'../components/ExpertAvailabilityPanel'
import{ExpertQueue}from'../components/ExpertQueue'
import{bootstrapGame,invoke,saveFacilitatorToken,saveFacilitatorGameCode,getFacilitatorGameCode,getFacilitatorToken}from'../lib/api'
import{ROUND_COPY}from'../content'
import{LESSONS}from'../learning'

function Login({onLogin}){const[code,setCode]=useState('FUTUROS26');const[pin,setPin]=useState('');const[err,setErr]=useState('');const[busy,setBusy]=useState(false);const[showCreate,setShowCreate]=useState(false);const[master,setMaster]=useState('');async function go(){setBusy(true);setErr('');try{const r=await invoke('facilitator-login',{game_code:code,pin},'facilitator');saveFacilitatorToken(r.token);saveFacilitatorGameCode(code);onLogin()}catch(e){setErr(e.message)}finally{setBusy(false)}}async function create(){setBusy(true);setErr('');try{await bootstrapGame({game_code:code,pin,bootstrap_secret:master});setShowCreate(false);setMaster('')}catch(e){setErr(e.message)}finally{setBusy(false)}}return <Layout subtitle="Facilitador"><div className="grid grid-2"><div className="card card-accent"><div className="eyebrow">CONTROL DOCENTE</div><h2>Entrar</h2><div className="form-row"><label>Código</label><input className="input" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></div><div className="form-row"><label>PIN</label><input className="input" type="password" value={pin} onChange={e=>setPin(e.target.value)}/></div>{err&&<div className="notice notice-red">{err}</div>}<button className="btn btn-primary" disabled={busy||code.length<4||pin.length<8} onClick={go}>Entrar</button></div><div className="card"><h3>Nueva partida</h3><button className="btn" onClick={()=>setShowCreate(v=>!v)}>{showCreate?'Cancelar':'Crear partida'}</button>{showCreate&&<><div className="form-row"><label>Clave maestra</label><input className="input" type="password" value={master} onChange={e=>setMaster(e.target.value)}/></div><button className="btn btn-primary" disabled={busy||master.length<12} onClick={create}>Crear</button></>}</div></div></Layout>}

function useRemote(){const[state,setState]=useState(null);const[err,setErr]=useState('');async function refresh(){try{setState(await invoke('leaderboard',{},'facilitator'));setErr('')}catch(e){setErr(e.message)}}useEffect(()=>{refresh();const i=setInterval(refresh,2500);return()=>clearInterval(i)},[]);return{state,err,refresh}}

function Console(){const{state,err,refresh}=useRemote();const[busy,setBusy]=useState(false);const[info,setInfo]=useState('');if(!state)return <Layout subtitle="Facilitador"><div className="card">Conectando… {err}</div></Layout>;const g=state.game,copy=ROUND_COPY[g.round],lesson=LESSONS[g.round];const pc=Number(g.player_count||0),hc=Number(g.human_count||0),bc=Number(g.bot_count||0);async function act(action,seconds=60){if(action==='reset'&&!confirm('¿Resetear sesión completa?'))return;setBusy(true);setInfo('');try{const r=await invoke('facilitator-transition',{action,seconds},'facilitator');if(action==='seed_bots')setInfo(`Ensayo: ${r.players} participantes, ${r.bots} bots.`);await refresh()}catch(e){alert(e.message)}finally{setBusy(false)}}const canLesson=['lobby','briefing'].includes(g.phase)&&hc>0;const canOpen=g.phase==='lesson';const canClose=['round','paused'].includes(g.phase);const canReveal=g.phase==='closed';const canTeach=g.phase==='reveal';const canCheck=g.phase==='teaching';const canNext=['microcheck','teaching','reveal'].includes(g.phase);const canTime=['round','paused'].includes(g.phase);const canSeed=['lobby','briefing'].includes(g.phase)&&pc<20;return <Layout subtitle="Facilitador" actions={<><span className="pill">Ronda <strong>{g.round}/4</strong></span><a className="btn btn-ghost" href="system-check.html" target="_blank" rel="noreferrer"><MonitorCheck size={15}/> Prueba previa</a><a className="btn btn-ghost" href={`wall.html?game=${encodeURIComponent(getFacilitatorGameCode())}`} target="_blank" rel="noreferrer">Abrir wall</a></>}>
<div className="grid grid-4"><div className="card"><div className="metric"><span>Estado</span><strong style={{fontSize:22}}>{g.phase.toUpperCase()}</strong><small>{g.public_message}</small></div></div><div className="card"><div className="metric"><span>Participantes</span><strong>{pc}/20</strong><small>{hc} humanos · {bc} bots</small></div></div><div className="card"><div className="metric"><span>Equipos listos</span><strong>{state.teams.filter(t=>t.locked).length}/4</strong><small>decisiones</small></div></div><div className="card"><div className="metric"><span>Bloque docente</span><strong>{lesson.minutes} min</strong><small>{lesson.title}</small></div></div></div>
{['lobby','briefing'].includes(g.phase)&&<><div className="section-title"><h2>Antes de la sesión</h2><p>Comprueba que los 20 participantes hayan ejecutado la prueba en Windows/macOS antes del chapter.</p></div><ReadinessPanel/></>}
<div className="section-title"><h2>1 · Enseñar</h2><p>La ronda no se puede abrir antes de presentar el concepto. Los poderes avanzados aparecen sólo cuando ya fueron explicados.</p></div><LessonPanel round={g.round} facilitator/>
<div className="card teaching-flow" style={{marginTop:16}}><div><b>Secuencia recomendada</b><p>Explica {lesson.minutes} min → demuestra 2–3 min → pulsa <b>Presentar concepto</b> → se revelan los nuevos poderes → envía a las 4 salas → abre laboratorio.</p></div><div className="fac-toolbar"><button className="btn btn-primary" disabled={busy||!canLesson} onClick={()=>act('lesson')}><Presentation size={16}/> Presentar concepto y poderes</button><button className="btn btn-primary" disabled={busy||!canOpen} onClick={()=>act('open')}><Play size={16}/> Abrir laboratorio</button></div></div>
{['lobby','briefing'].includes(g.phase)&&<><div className="section-title"><h2>Ensayo</h2><p>Para probar sin 20 personas.</p></div><div className="card"><div className="fac-toolbar"><button className="btn" disabled={busy||!canSeed} onClick={()=>act('seed_bots')}><Bot size={16}/> Completar con bots</button><a className="btn" href="play.html" target="_blank" rel="noreferrer"><Users size={16}/> Abrir participante</a></div></div></>}
{hc===0&&<div className="notice notice-red" style={{marginTop:12}}>Debe existir al menos un humano antes de presentar la mini-clase.</div>}{info&&<div className="notice notice-green" style={{marginTop:12}}>{info}</div>}
<div className="section-title"><h2>2 · Recursos humanos opcionales</h2><p>El Game Master dirige y no se compra. Define cuántas llamadas pueden atender los otros tres facilitadores expertos durante esta ronda.</p></div><ExpertAvailabilityPanel round={g.round}/><ExpertQueue audit={state.audit||[]}/>
<div className="section-title"><h2>3 · Dirigir el juego</h2><p>Reveal y cierre pedagógico ocurren en sala principal.</p></div><div className="card"><div className="fac-toolbar"><button className="btn" disabled={busy||!canClose} onClick={()=>act('close')}><LockKeyhole size={16}/> Cerrar decisiones</button><button className="btn" disabled={busy||!canReveal} onClick={()=>act('reveal')}><Eye size={16}/> Revelar</button><button className="btn" disabled={busy||!canTeach} onClick={()=>act('teach')}><GraduationCap size={16}/> Cierre pedagógico</button><button className="btn" disabled={busy||!canCheck} onClick={()=>act('microcheck')}>Microcheck</button><button className="btn" disabled={busy||!canNext} onClick={()=>act('next')}><SkipForward size={16}/> Siguiente ronda</button><button className="btn" disabled={busy||!canTime} onClick={()=>act('add_time',60)}><Clock3 size={16}/> +60 s</button>{g.phase==='paused'?<button className="btn btn-primary" onClick={()=>act('resume')}><Play size={16}/> Reanudar</button>:<button className="btn" disabled={busy||g.phase!=='round'} onClick={()=>act('pause')}><Pause size={16}/> Pausar</button>}<button className="btn" disabled={busy||g.phase==='round'} onClick={()=>act('reset')}><RotateCcw size={16}/> Reset</button></div></div>
{err&&<div className="notice notice-red" style={{marginTop:12}}>Conexión: {err}</div>}
<div className="section-title"><h2>4 · Observar</h2><p>El leaderboard es determinista; los hallazgos de rol y microchecks miden aprendizaje pero no añaden puntos subjetivos.</p></div><div className="card"><div className="team-status header"><div>Equipo</div><div>H/B</div><div>Online</div><div>Locked</div><div>Impacto</div><div>Evid.</div><div>Checks</div></div>{state.teams.map(t=><div className="team-status" key={t.id}><div><b>{t.name}</b></div><div>{t.humans||0}/{t.bots||0}</div><div>{t.online||0}</div><div>{t.locked?'✓':'…'}</div><div>{t.score.impact}</div><div>{t.score.evidence}</div><div>{t.check_correct||0}</div></div>)}</div><div className="grid grid-2" style={{marginTop:16}}><div className="card"><h3>Leaderboard</h3><Leaderboard state={state}/></div><div className="card"><h3>Auditoría</h3><div className="audit">{(state.audit||[]).map((e,i)=><div className="audit-row" key={i}><b>{new Date(e.at).toLocaleTimeString()}</b> · {e.type}</div>)}</div></div></div>
</Layout>}

export default function SecureFacilitatorLearning(){const[token,setToken]=useState(()=>getFacilitatorToken());return token?<Console/>:<Login onLogin={()=>setToken(getFacilitatorToken())}/>}
