import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
const out=resolve('src/demo/groundTruth.generated.js');mkdirSync(dirname(out),{recursive:true})
const customers=[
['C01','Laura','Patrimonio alto',.96,.95,.96],['C02','Felipe','Patrimonio alto',.93,.91,.93],['C03','Mariana','Tradicional',.90,.86,.90],['C04','Samuel','Tradicional',.87,.84,.87],['C05','Nicolás','Jóvenes digitales',.84,.66,.84],['C06','Valentina','Jóvenes digitales',.82,.61,.82],['C07','Camilo','Ingreso medio',.79,.55,.79],['C08','Diana','Ingreso medio',.77,.52,.77],['C09','Sara','Jóvenes digitales',.73,.45,.73],['C10','Andrés','Ingreso medio',.69,.42,.69],['C11','Mateo','Ingreso medio',.64,.37,.64],['C12','Paula','Jóvenes digitales',.61,.34,.61],['C13','Juliana','Tradicional',.59,.55,.59],['C14','Daniel','Tradicional',.56,.53,.56],['C15','Tomás','Mora alta',.51,.57,.51],['C16','Lucía','Mora alta',.48,.54,.48],['C17','Santiago','Ingreso medio',.47,.25,.47],['C18','Carolina','Jóvenes digitales',.45,.19,.45],['C19','Juan','Patrimonio alto',.43,.42,.43],['C20','Mónica','Tradicional',.41,.39,.41],['C21','Esteban','Mora alta',.36,.42,.36],['C22','Natalia','Jóvenes digitales',.35,.12,.35],['C23','Alejandro','Ingreso medio',.33,.14,.33],['C24','Gabriela','Mora alta',.29,.35,.29]
].map(([id,name,segment,score,p0,p1])=>({id,name,segment,score,p0,p1,cost:1,risk:segment==='Mora alta'?3:1,__demoSecretMarker:'DEMO_GROUND_TRUTH_DO_NOT_SHIP_7XQ9'}))
const roleCards={business:'Cobranza prioriza a los clientes con mayor dificultad de pago.',data:'La mora previa promedio de los llamados es aproximadamente el doble de la de los no llamados.',context:'Antes de esta estrategia, los clientes con mayor mora ya pagaban menos.',risk:'Por política operativa, los clientes con más de 90 días de mora casi siempre reciben llamada.',integrator:'Dirección exige recomendar: cancelar, mantener tal cual o rediseñar la estrategia.'}
const segments=[{id:'digital',name:'Jóvenes digitales',effect:16,risk:1},{id:'middle',name:'Ingreso medio',effect:11,risk:1},{id:'traditional',name:'Tradicional',effect:2,risk:1},{id:'wealth',name:'Patrimonio alto',effect:1,risk:1},{id:'arrears',name:'Mora alta',effect:-5,risk:5}]
const answers={1:'B',2:'Los grupos no son comparables desde antes',3:'6 puntos porcentuales',4:'Priorizar segmentos con efecto positivo y evitar el segmento negativo'}
writeFileSync(out,`// AUTO-GENERATED FOR LOCAL FACILITATOR REHEARSAL. DO NOT COMMIT.\nexport const CUSTOMERS=${JSON.stringify(customers,null,2)}\nexport const ROUND2_CARDS=${JSON.stringify(roleCards,null,2)}\nexport const SEGMENTS=${JSON.stringify(segments,null,2)}\nexport const ANSWERS=${JSON.stringify(answers,null,2)}\n`)
console.log(`generated ${out}`)
